package com.skkil.sync.common.exception;

public enum ErrorCode {
  OAUTH2_ACCOUNT_CANNOT_BE_DELETED,
  OAUTH2_ACCOUNT_CANNOT_BE_LINKED,
  USER_NOT_FOUND,
  USER_ALREADY_EXISTS,
  USER_CANNOT_FOLLOW_SELF,
  PROVIDER_NOT_FOUND,
  PROVIDER_NOT_VERIFIED,
  EXPERIENCE_NOT_FOUND,
  REFLECTION_NOT_FOUND,
  MEDIA_NOT_FOUND,
  MESSAGE_TO_SELF
}
