package com.skkil.sync.common.exception;

public enum ErrorCode {
  USER_NOT_FOUND,
  USER_ALREADY_EXISTS,
  USER_CANNOT_FOLLOW_SELF,
  PROVIDER_NOT_FOUND,
  PROVIDER_NOT_VERIFIED,
  EXPERIENCE_NOT_FOUND,
  MEDIA_NOT_FOUND,
  MESSAGE_TO_SELF
}
