--liquibase formatted sql
--changeset skkil:00001-post-moderation
--
ALTER TABLE posts
ADD COLUMN visibility VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
ADD COLUMN hidden_at TIMESTAMPTZ DEFAULT NULL,
ADD COLUMN hidden_by BIGINT DEFAULT NULL,
ADD COLUMN hidden_reason TEXT DEFAULT NULL,
ADD CONSTRAINT fk_posts_hidden_by_users FOREIGN KEY (hidden_by) REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE post_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    post_id BIGINT NOT NULL,
    reporter_id BIGINT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT DEFAULT NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    resolution_note TEXT,
    FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY(reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE(post_id, reporter_id)
);

CREATE INDEX idx_posts_visibility ON posts(visibility);

CREATE INDEX idx_post_reports_status_created_id ON post_reports(status, created_at DESC, id DESC);

CREATE INDEX idx_post_reports_post_status ON post_reports(post_id, status);
