CREATE TABLE providers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_verified BOOLEAN DEFAULT FALSE
);

CREATE TABLE schools (
    id BIGINT PRIMARY KEY,
    school_type VARCHAR(100) NOT NULL,
    FOREIGN KEY(id) REFERENCES providers(id)
)
