--liquibase formatted sql
--changeset skkil:00000-initial-schema
--
CREATE EXTENSION IF NOT EXISTS vector;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID char(36) NOT NULL,
    SESSION_ID char(36) NOT NULL,
    CREATION_TIME bigint NOT NULL,
    LAST_ACCESS_TIME bigint NOT NULL,
    MAX_INACTIVE_INTERVAL int NOT NULL,
    EXPIRY_TIME bigint NOT NULL,
    PRINCIPAL_NAME varchar(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);

CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);

CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID char(36) NOT NULL,
    ATTRIBUTE_NAME varchar(200) NOT NULL,
    ATTRIBUTE_BYTES bytea NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);

CREATE TABLE bucket (
    id varchar(255) NOT NULL,
    state bytea,
    expires_at bigint,
    CONSTRAINT bucket_pk PRIMARY KEY (id)
);

CREATE INDEX bucket_expires_at_idx ON bucket (expires_at);

CREATE TABLE media_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50) NOT NULL,
    media_type VARCHAR(255) NOT NULL,
    bucket VARCHAR(255) NOT NULL,
    KEY VARCHAR(255) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    email VARCHAR(255) NOT NULL UNIQUE,
    handle VARCHAR(255) UNIQUE,
    hashed_password VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    contacts JSONB,
    profession VARCHAR(255),
    bio TEXT,
    role VARCHAR(50) DEFAULT 'USER',
    is_onboarded BOOLEAN DEFAULT FALSE,
    is_email_verified BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    profile_image_id BIGINT,
    follower_count BIGINT NOT NULL DEFAULT 0,
    following_count BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY(profile_image_id) REFERENCES media_files (id) ON DELETE
    SET
        NULL
);

ALTER TABLE
    media_files
ADD
    COLUMN uploader_id BIGINT;

ALTER TABLE
    media_files
ADD
    CONSTRAINT fk_media_files_users FOREIGN KEY (uploader_id) REFERENCES users (id) ON DELETE
SET
    NULL;

CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY,
    theme VARCHAR(20),
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE user_oauth2_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    oauth_provider VARCHAR(255) NOT NULL,
    oauth_provider_user_id VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (user_id, oauth_provider)
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    handle VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    website_url VARCHAR(255),
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    follower_count BIGINT NOT NULL DEFAULT 0,
    icon_media_id BIGINT,
    FOREIGN KEY(icon_media_id) REFERENCES media_files (id) ON DELETE
    SET
        NULL
);

CREATE TABLE teammates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_owner BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(50) NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
    UNIQUE (project_id, user_id)
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    slug VARCHAR(255) NOT NULL UNIQUE,
    author_id BIGINT NOT NULL,
    project_id BIGINT,
    title VARCHAR(255),
    post_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    content TEXT,
    summary TEXT,
    like_count BIGINT NOT NULL DEFAULT 0,
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    visibility VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    hidden_at TIMESTAMPTZ DEFAULT NULL,
    hidden_by BIGINT DEFAULT NULL,
    hidden_reason TEXT DEFAULT NULL,
    FOREIGN KEY(author_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE
    SET
        NULL,
    FOREIGN KEY(hidden_by) REFERENCES users (id) ON DELETE
    SET
        NULL
);

CREATE TABLE post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
    UNIQUE (user_id, post_id)
);

CREATE TABLE post_media_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    post_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    sort_order INT NOT NULL,
    FOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE,
    FOREIGN KEY(media_id) REFERENCES media_files (id) ON DELETE CASCADE,
    UNIQUE (post_id, media_id),
    UNIQUE(post_id, sort_order)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    deleted_at TIMESTAMPTZ,
    FOREIGN KEY(author_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY(post_id) REFERENCES posts(id)
);

CREATE TABLE post_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    post_id BIGINT NOT NULL,
    reporter_id BIGINT NOT NULL,
    reason VARCHAR(50) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT DEFAULT NULL,
    reviewed_at TIMESTAMPTZ DEFAULT NULL,
    resolution_note TEXT,
    FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY(reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE(post_id, reporter_id)
);

CREATE TABLE user_follow_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    follower_id BIGINT NOT NULL,
    followee_id BIGINT NOT NULL,
    FOREIGN KEY(follower_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(followee_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (follower_id, followee_id)
);

CREATE INDEX idx_user_follow_relationships_followee ON user_follow_relationships(followee_id);

CREATE TABLE project_follow_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    follower_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    FOREIGN KEY(follower_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
    UNIQUE (follower_id, project_id)
);

CREATE INDEX idx_project_follow_relationships_project ON project_follow_relationships(project_id);

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL UNIQUE,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE post_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    date DATE NOT NULL,
    count BIGINT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, date)
);

CREATE TABLE post_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,
    UNIQUE (user_id, post_id)
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    post_count BIGINT NOT NULL DEFAULT 0,
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    project_id BIGINT,
    FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE,
    UNIQUE (project_id, name)
);

CREATE UNIQUE INDEX idx_tags_name_global ON tags (name) WHERE project_id IS NULL;

CREATE TABLE post_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    post_id BIGINT NOT NULL,
    embedding VECTOR(1536) NOT NULL,
    FOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE,
    UNIQUE (post_id)
);

CREATE TABLE post_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    post_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    FOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE,
    FOREIGN KEY(tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    UNIQUE (post_id, tag_id)
);

CREATE TABLE project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL,
    inviter_id BIGINT NOT NULL,
    invitee_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE,
    FOREIGN KEY(inviter_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY(invitee_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_project_invitations_invitee_id ON project_invitations (invitee_id);

CREATE INDEX idx_post_bookmarks_user_created_id ON post_bookmarks (user_id, created_at DESC, id DESC);

CREATE INDEX idx_post_bookmarks_post_id ON post_bookmarks (post_id);

CREATE INDEX idx_post_likes_user_created_id ON post_likes (user_id, created_at DESC, id DESC);

CREATE INDEX idx_post_likes_post_id ON post_likes (post_id);

CREATE INDEX idx_post_embeddings_embedding_hnsw ON post_embeddings USING hnsw (embedding vector_cosine_ops);

CREATE INDEX idx_posts_content_gin ON posts USING gin (content gin_trgm_ops);

CREATE INDEX idx_posts_status_created_id ON posts(status, created_at DESC, id DESC);

CREATE INDEX idx_posts_visibility ON posts(visibility);

CREATE INDEX idx_post_reports_status_created_id ON post_reports(status, created_at DESC, id DESC);

CREATE INDEX idx_post_reports_post_status ON post_reports(post_id, status);

CREATE INDEX idx_comments_post_created_id ON comments(post_id, created_at DESC, id DESC);
