databaseChangeLog:
  - changeSet:
      id: 00018-create-table-job-application-files
      author: hyoungjoojin
      preConditions:
        - and:
            - tableExists:
                tableName: job_applications
            - tableExists:
                tableName: media_files
            - not:
                tableExists:
                  tableName: job_application_files
      changes:
        - createTable:
            tableName: job_application_files
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: updated_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: job_application_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: media_id
                  type: BIGINT
                  constraints:
                    nullable: false
        - addForeignKeyConstraint:
            constraintName: fk_job_application_files_job_applications
            baseTableName: job_application_files
            baseColumnNames: job_application_id
            referencedTableName: job_applications
            referencedColumnNames: id
            onDelete: CASCADE
        - addForeignKeyConstraint:
            constraintName: fk_job_application_files_media
            baseTableName: job_application_files
            baseColumnNames: media_id
            referencedTableName: media_files
            referencedColumnNames: id
            onDelete: CASCADE
