apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: web-secret
  namespace: sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: web-secret
    creationPolicy: Owner
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: sync/local/web/app
        property: BETTER_AUTH_SECRET
