/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  GetUserPreferencesResponse,
  UpdateUserPreferencesRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getUserPreferencesResponse200 = {
  data: GetUserPreferencesResponse;
  status: 200;
};

export type getUserPreferencesResponseSuccess =
  getUserPreferencesResponse200 & {
    headers: Headers;
  };
export type getUserPreferencesResponse = getUserPreferencesResponseSuccess;

export const getGetUserPreferencesUrl = () => {
  return `/preferences/me`;
};

/**
 * Get User Preferences
 * @summary Get User Preferences
 */
export const getUserPreferences = async (
  options?: RequestInit,
): Promise<getUserPreferencesResponse> => {
  return api<getUserPreferencesResponse>(getGetUserPreferencesUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetUserPreferencesQueryKey = () => {
  return [`/preferences/me`] as const;
};

export const getGetUserPreferencesQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserPreferences>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getUserPreferences>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserPreferencesQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserPreferences>>
  > = ({ signal }) => getUserPreferences({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserPreferences>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserPreferencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserPreferences>>
>;
export type GetUserPreferencesQueryError = ErrorType<unknown>;

export function useGetUserPreferences<
  TData = Awaited<ReturnType<typeof getUserPreferences>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserPreferences>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPreferences>>,
          TError,
          Awaited<ReturnType<typeof getUserPreferences>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserPreferences<
  TData = Awaited<ReturnType<typeof getUserPreferences>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserPreferences>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPreferences>>,
          TError,
          Awaited<ReturnType<typeof getUserPreferences>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserPreferences<
  TData = Awaited<ReturnType<typeof getUserPreferences>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserPreferences>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User Preferences
 */

export function useGetUserPreferences<
  TData = Awaited<ReturnType<typeof getUserPreferences>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserPreferences>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserPreferencesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateUserPreferencesResponse204 = {
  data: void;
  status: 204;
};

export type updateUserPreferencesResponseSuccess =
  updateUserPreferencesResponse204 & {
    headers: Headers;
  };
export type updateUserPreferencesResponse =
  updateUserPreferencesResponseSuccess;

export const getUpdateUserPreferencesUrl = () => {
  return `/preferences/me`;
};

/**
 * Update User Preferences
 * @summary Update User Preferences
 */
export const updateUserPreferences = async (
  updateUserPreferencesRequest?: UpdateUserPreferencesRequest,
  options?: RequestInit,
): Promise<updateUserPreferencesResponse> => {
  return api<updateUserPreferencesResponse>(getUpdateUserPreferencesUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateUserPreferencesRequest),
  });
};

export const getUpdateUserPreferencesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserPreferences>>,
    TError,
    { data?: UpdateUserPreferencesRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserPreferences>>,
  TError,
  { data?: UpdateUserPreferencesRequest },
  TContext
> => {
  const mutationKey = ['updateUserPreferences'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserPreferences>>,
    { data?: UpdateUserPreferencesRequest }
  > = (props) => {
    const { data } = props ?? {};

    return updateUserPreferences(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserPreferencesMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserPreferences>>
>;
export type UpdateUserPreferencesMutationBody =
  | UpdateUserPreferencesRequest
  | undefined;
export type UpdateUserPreferencesMutationError = ErrorType<unknown>;

/**
 * @summary Update User Preferences
 */
export const useUpdateUserPreferences = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserPreferences>>,
      TError,
      { data?: UpdateUserPreferencesRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserPreferences>>,
  TError,
  { data?: UpdateUserPreferencesRequest },
  TContext
> => {
  return useMutation(
    getUpdateUserPreferencesMutationOptions(options),
    queryClient,
  );
};
