/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreateCommentRequest,
  CreateCommentResponse,
  GetCommentsResponse,
  UpdateCommentRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Delete Comment
 * @summary Delete Comment
 */
export type deleteCommentResponse204 = {
  data: void;
  status: 204;
};

export type deleteCommentResponseSuccess = deleteCommentResponse204 & {
  headers: Headers;
};
export type deleteCommentResponse = deleteCommentResponseSuccess;

export const getDeleteCommentUrl = (commentId: string) => {
  return `/comments/${commentId}`;
};

export const deleteComment = async (
  commentId: string,
  options?: RequestInit,
): Promise<deleteCommentResponse> => {
  return api<deleteCommentResponse>(getDeleteCommentUrl(commentId), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteComment>>,
    TError,
    { commentId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: string },
  TContext
> => {
  const mutationKey = ['deleteComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteComment>>,
    { commentId: string }
  > = (props) => {
    const { commentId } = props ?? {};

    return deleteComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteComment>>
>;

export type DeleteCommentMutationError = ErrorType<unknown>;

/**
 * @summary Delete Comment
 */
export const useDeleteComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteComment>>,
      TError,
      { commentId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: string },
  TContext
> => {
  return useMutation(getDeleteCommentMutationOptions(options), queryClient);
};
/**
 * Update Comment
 * @summary Update Comment
 */
export type updateCommentResponse204 = {
  data: void;
  status: 204;
};

export type updateCommentResponseSuccess = updateCommentResponse204 & {
  headers: Headers;
};
export type updateCommentResponse = updateCommentResponseSuccess;

export const getUpdateCommentUrl = (commentId: string) => {
  return `/comments/${commentId}`;
};

export const updateComment = async (
  commentId: string,
  updateCommentRequest: UpdateCommentRequest,
  options?: RequestInit,
): Promise<updateCommentResponse> => {
  return api<updateCommentResponse>(getUpdateCommentUrl(commentId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCommentRequest),
  });
};

export const getUpdateCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateComment>>,
    TError,
    { commentId: string; data: UpdateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { commentId: string; data: UpdateCommentRequest },
  TContext
> => {
  const mutationKey = ['updateComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateComment>>,
    { commentId: string; data: UpdateCommentRequest }
  > = (props) => {
    const { commentId, data } = props ?? {};

    return updateComment(commentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateComment>>
>;
export type UpdateCommentMutationBody = UpdateCommentRequest;
export type UpdateCommentMutationError = ErrorType<unknown>;

/**
 * @summary Update Comment
 */
export const useUpdateComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateComment>>,
      TError,
      { commentId: string; data: UpdateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { commentId: string; data: UpdateCommentRequest },
  TContext
> => {
  return useMutation(getUpdateCommentMutationOptions(options), queryClient);
};
/**
 * Create Comment
 * @summary Create Comment
 */
export type createCommentResponse201 = {
  data: CreateCommentResponse;
  status: 201;
};

export type createCommentResponseSuccess = createCommentResponse201 & {
  headers: Headers;
};
export type createCommentResponse = createCommentResponseSuccess;

export const getCreateCommentUrl = (reflectionId: string) => {
  return `/reflections/${reflectionId}/comments`;
};

export const createComment = async (
  reflectionId: string,
  createCommentRequest: CreateCommentRequest,
  options?: RequestInit,
): Promise<createCommentResponse> => {
  return api<createCommentResponse>(getCreateCommentUrl(reflectionId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCommentRequest),
  });
};

export const getCreateCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createComment>>,
    TError,
    { reflectionId: string; data: CreateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { reflectionId: string; data: CreateCommentRequest },
  TContext
> => {
  const mutationKey = ['createComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createComment>>,
    { reflectionId: string; data: CreateCommentRequest }
  > = (props) => {
    const { reflectionId, data } = props ?? {};

    return createComment(reflectionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createComment>>
>;
export type CreateCommentMutationBody = CreateCommentRequest;
export type CreateCommentMutationError = ErrorType<unknown>;

/**
 * @summary Create Comment
 */
export const useCreateComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createComment>>,
      TError,
      { reflectionId: string; data: CreateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { reflectionId: string; data: CreateCommentRequest },
  TContext
> => {
  return useMutation(getCreateCommentMutationOptions(options), queryClient);
};
/**
 * Get Reflection Comments
 * @summary Get Reflection Comments
 */
export type getReflectionCommentsResponse200 = {
  data: GetCommentsResponse;
  status: 200;
};

export type getReflectionCommentsResponseSuccess =
  getReflectionCommentsResponse200 & {
    headers: Headers;
  };
export type getReflectionCommentsResponse =
  getReflectionCommentsResponseSuccess;

export const getGetReflectionCommentsUrl = (slug: string) => {
  return `/reflections/${slug}/comments`;
};

export const getReflectionComments = async (
  slug: string,
  options?: RequestInit,
): Promise<getReflectionCommentsResponse> => {
  return api<getReflectionCommentsResponse>(getGetReflectionCommentsUrl(slug), {
    ...options,
    method: 'GET',
  });
};

export const getGetReflectionCommentsQueryKey = (slug: string) => {
  return [`/reflections/${slug}/comments`] as const;
};

export const getGetReflectionCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getReflectionComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReflectionComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetReflectionCommentsQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReflectionComments>>
  > = ({ signal }) =>
    getReflectionComments(slug, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReflectionComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReflectionCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReflectionComments>>
>;
export type GetReflectionCommentsQueryError = ErrorType<unknown>;

export function useGetReflectionComments<
  TData = Awaited<ReturnType<typeof getReflectionComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReflectionComments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReflectionComments>>,
          TError,
          Awaited<ReturnType<typeof getReflectionComments>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReflectionComments<
  TData = Awaited<ReturnType<typeof getReflectionComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReflectionComments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReflectionComments>>,
          TError,
          Awaited<ReturnType<typeof getReflectionComments>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReflectionComments<
  TData = Awaited<ReturnType<typeof getReflectionComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReflectionComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Reflection Comments
 */

export function useGetReflectionComments<
  TData = Awaited<ReturnType<typeof getReflectionComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReflectionComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReflectionCommentsQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
