/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreateCommentRequest,
  CreateCommentResponse,
  GetCommentsResponse,
  GetPostCommentsParams,
  UpdateCommentRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type deleteCommentResponse204 = {
  data: void;
  status: 204;
};

export type deleteCommentResponseSuccess = deleteCommentResponse204 & {
  headers: Headers;
};
export type deleteCommentResponse = deleteCommentResponseSuccess;

export const getDeleteCommentUrl = (commentId: string) => {
  return `/comments/${commentId}`;
};

/**
 * Delete Comment
 * @summary Delete Comment
 */
export const deleteComment = async (
  commentId: string,
  options?: RequestInit,
): Promise<deleteCommentResponse> => {
  return api<deleteCommentResponse>(getDeleteCommentUrl(commentId), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteComment>>,
    TError,
    { commentId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: string },
  TContext
> => {
  const mutationKey = ['deleteComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteComment>>,
    { commentId: string }
  > = (props) => {
    const { commentId } = props ?? {};

    return deleteComment(commentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteComment>>
>;

export type DeleteCommentMutationError = ErrorType<unknown>;

/**
 * @summary Delete Comment
 */
export const useDeleteComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteComment>>,
      TError,
      { commentId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteComment>>,
  TError,
  { commentId: string },
  TContext
> => {
  return useMutation(getDeleteCommentMutationOptions(options), queryClient);
};
export type updateCommentResponse204 = {
  data: void;
  status: 204;
};

export type updateCommentResponseSuccess = updateCommentResponse204 & {
  headers: Headers;
};
export type updateCommentResponse = updateCommentResponseSuccess;

export const getUpdateCommentUrl = (commentId: string) => {
  return `/comments/${commentId}`;
};

/**
 * Update Comment
 * @summary Update Comment
 */
export const updateComment = async (
  commentId: string,
  updateCommentRequest?: UpdateCommentRequest,
  options?: RequestInit,
): Promise<updateCommentResponse> => {
  return api<updateCommentResponse>(getUpdateCommentUrl(commentId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCommentRequest),
  });
};

export const getUpdateCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateComment>>,
    TError,
    { commentId: string; data?: UpdateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { commentId: string; data?: UpdateCommentRequest },
  TContext
> => {
  const mutationKey = ['updateComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateComment>>,
    { commentId: string; data?: UpdateCommentRequest }
  > = (props) => {
    const { commentId, data } = props ?? {};

    return updateComment(commentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateComment>>
>;
export type UpdateCommentMutationBody = UpdateCommentRequest | undefined;
export type UpdateCommentMutationError = ErrorType<unknown>;

/**
 * @summary Update Comment
 */
export const useUpdateComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateComment>>,
      TError,
      { commentId: string; data?: UpdateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateComment>>,
  TError,
  { commentId: string; data?: UpdateCommentRequest },
  TContext
> => {
  return useMutation(getUpdateCommentMutationOptions(options), queryClient);
};
export type getPostCommentsResponse200 = {
  data: GetCommentsResponse;
  status: 200;
};

export type getPostCommentsResponseSuccess = getPostCommentsResponse200 & {
  headers: Headers;
};
export type getPostCommentsResponse = getPostCommentsResponseSuccess;

export const getGetPostCommentsUrl = (
  slug: string,
  params?: GetPostCommentsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/posts/${slug}/comments?${stringifiedParams}`
    : `/posts/${slug}/comments`;
};

/**
 * Get Post Comments
 * @summary Get Post Comments
 */
export const getPostComments = async (
  slug: string,
  params?: GetPostCommentsParams,
  options?: RequestInit,
): Promise<getPostCommentsResponse> => {
  return api<getPostCommentsResponse>(getGetPostCommentsUrl(slug, params), {
    ...options,
    method: 'GET',
  });
};

export const getGetPostCommentsInfiniteQueryKey = (
  slug: string,
  params?: GetPostCommentsParams,
) => {
  return [
    'infinite',
    `/posts/${slug}/comments`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetPostCommentsQueryKey = (
  slug: string,
  params?: GetPostCommentsParams,
) => {
  return [`/posts/${slug}/comments`, ...(params ? [params] : [])] as const;
};

export const getGetPostCommentsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostComments>>,
    GetPostCommentsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData,
        QueryKey,
        GetPostCommentsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPostCommentsInfiniteQueryKey(slug, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPostComments>>,
    QueryKey,
    GetPostCommentsParams['after']
  > = ({ signal, pageParam }) =>
    getPostComments(
      slug,
      { ...params, after: pageParam ?? params?.['after'] },
      { signal, ...requestOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getPostComments>>,
    TError,
    TData,
    QueryKey,
    GetPostCommentsParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostCommentsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostComments>>
>;
export type GetPostCommentsInfiniteQueryError = ErrorType<unknown>;

export function useGetPostCommentsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostComments>>,
    GetPostCommentsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params: undefined | GetPostCommentsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData,
        QueryKey,
        GetPostCommentsParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostComments>>,
          TError,
          Awaited<ReturnType<typeof getPostComments>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostCommentsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostComments>>,
    GetPostCommentsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData,
        QueryKey,
        GetPostCommentsParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostComments>>,
          TError,
          Awaited<ReturnType<typeof getPostComments>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostCommentsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostComments>>,
    GetPostCommentsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData,
        QueryKey,
        GetPostCommentsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Post Comments
 */

export function useGetPostCommentsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostComments>>,
    GetPostCommentsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData,
        QueryKey,
        GetPostCommentsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostCommentsInfiniteQueryOptions(
    slug,
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetPostCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPostCommentsQueryKey(slug, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostComments>>> = ({
    signal,
  }) => getPostComments(slug, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostComments>>
>;
export type GetPostCommentsQueryError = ErrorType<unknown>;

export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params: undefined | GetPostCommentsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostComments>>,
          TError,
          Awaited<ReturnType<typeof getPostComments>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostComments>>,
          TError,
          Awaited<ReturnType<typeof getPostComments>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Post Comments
 */

export function useGetPostComments<
  TData = Awaited<ReturnType<typeof getPostComments>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  params?: GetPostCommentsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostCommentsQueryOptions(slug, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createCommentResponse201 = {
  data: CreateCommentResponse;
  status: 201;
};

export type createCommentResponseSuccess = createCommentResponse201 & {
  headers: Headers;
};
export type createCommentResponse = createCommentResponseSuccess;

export const getCreateCommentUrl = (slug: string) => {
  return `/posts/${slug}/comments`;
};

/**
 * Create Comment
 * @summary Create Comment
 */
export const createComment = async (
  slug: string,
  createCommentRequest?: CreateCommentRequest,
  options?: RequestInit,
): Promise<createCommentResponse> => {
  return api<createCommentResponse>(getCreateCommentUrl(slug), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCommentRequest),
  });
};

export const getCreateCommentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createComment>>,
    TError,
    { slug: string; data?: CreateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { slug: string; data?: CreateCommentRequest },
  TContext
> => {
  const mutationKey = ['createComment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createComment>>,
    { slug: string; data?: CreateCommentRequest }
  > = (props) => {
    const { slug, data } = props ?? {};

    return createComment(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createComment>>
>;
export type CreateCommentMutationBody = CreateCommentRequest | undefined;
export type CreateCommentMutationError = ErrorType<unknown>;

/**
 * @summary Create Comment
 */
export const useCreateComment = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createComment>>,
      TError,
      { slug: string; data?: CreateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createComment>>,
  TError,
  { slug: string; data?: CreateCommentRequest },
  TContext
> => {
  return useMutation(getCreateCommentMutationOptions(options), queryClient);
};
