apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: sync/local/postgres/password
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: sync/local/postgres/password
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: sync/local/postgres/password
        property: dbname
