/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type { GetProjectExperiencesResponse } from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get project experiences for a user profile
 * @summary Get Project Experiences
 */
export type getProjectExperiencesResponse200 = {
  data: GetProjectExperiencesResponse;
  status: 200;
};

export type getProjectExperiencesResponseSuccess =
  getProjectExperiencesResponse200 & {
    headers: Headers;
  };
export type getProjectExperiencesResponse =
  getProjectExperiencesResponseSuccess;

export const getGetProjectExperiencesUrl = (userId: string) => {
  return `/profiles/${userId}/experiences/projects`;
};

export const getProjectExperiences = async (
  userId: string,
  options?: RequestInit,
): Promise<getProjectExperiencesResponse> => {
  return api<getProjectExperiencesResponse>(
    getGetProjectExperiencesUrl(userId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetProjectExperiencesQueryKey = (userId: string) => {
  return [`/profiles/${userId}/experiences/projects`] as const;
};

export const getGetProjectExperiencesQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectExperiences>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectExperiences>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectExperiencesQueryKey(userId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectExperiences>>
  > = ({ signal }) =>
    getProjectExperiences(userId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectExperiences>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectExperiencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectExperiences>>
>;
export type GetProjectExperiencesQueryError = ErrorType<unknown>;

export function useGetProjectExperiences<
  TData = Awaited<ReturnType<typeof getProjectExperiences>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectExperiences>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectExperiences>>,
          TError,
          Awaited<ReturnType<typeof getProjectExperiences>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectExperiences<
  TData = Awaited<ReturnType<typeof getProjectExperiences>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectExperiences>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectExperiences>>,
          TError,
          Awaited<ReturnType<typeof getProjectExperiences>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectExperiences<
  TData = Awaited<ReturnType<typeof getProjectExperiences>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectExperiences>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Experiences
 */

export function useGetProjectExperiences<
  TData = Awaited<ReturnType<typeof getProjectExperiences>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectExperiences>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectExperiencesQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
