package com.skkil.sync.notification.constant;

public enum NotificationType {
  WELCOME,
  NEW_COMMENT,
  NEW_LIKE,
  NEW_FOLLOWER,
  PROJECT_INVITATION,
  PROJECT_INVITATION_ACCEPTED,
  PROJECT_INVITATION_DECLINED,
  PROJECT_JOIN_REQUEST,
  PROJECT_JOIN_REQUEST_APPROVED,
  PROJECT_JOIN_REQUEST_DECLINED,
  NEW_MESSAGE,
}
