/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type { SearchTagsParams, SearchTagsResponse } from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 검색어로 태그를 검색합니다.
 * @summary Search Tags
 */
export type searchTagsResponse200 = {
  data: SearchTagsResponse;
  status: 200;
};

export type searchTagsResponseSuccess = searchTagsResponse200 & {
  headers: Headers;
};
export type searchTagsResponse = searchTagsResponseSuccess;

export const getSearchTagsUrl = (params: SearchTagsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/search/tags?${stringifiedParams}`
    : `/search/tags`;
};

export const searchTags = async (
  params: SearchTagsParams,
  options?: RequestInit,
): Promise<searchTagsResponse> => {
  return api<searchTagsResponse>(getSearchTagsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchTagsQueryKey = (params?: SearchTagsParams) => {
  return [`/search/tags`, ...(params ? [params] : [])] as const;
};

export const getSearchTagsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchTags>>,
  TError = ErrorType<unknown>,
>(
  params: SearchTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchTagsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchTags>>> = ({
    signal,
  }) => searchTags(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchTags>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchTagsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchTags>>
>;
export type SearchTagsQueryError = ErrorType<unknown>;

export function useSearchTags<
  TData = Awaited<ReturnType<typeof searchTags>>,
  TError = ErrorType<unknown>,
>(
  params: SearchTagsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchTags<
  TData = Awaited<ReturnType<typeof searchTags>>,
  TError = ErrorType<unknown>,
>(
  params: SearchTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchTags<
  TData = Awaited<ReturnType<typeof searchTags>>,
  TError = ErrorType<unknown>,
>(
  params: SearchTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Tags
 */

export function useSearchTags<
  TData = Awaited<ReturnType<typeof searchTags>>,
  TError = ErrorType<unknown>,
>(
  params: SearchTagsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchTagsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
