/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreateContestOccurrenceRequest,
  GetContestOccurrenceResponse,
  GetContestOccurrencesByContestParams,
  GetContestOccurrencesResponse,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get Contest Occurrences by Contest
 * @summary Get Contest Occurrences by Contest
 */
export type getContestOccurrencesByContestResponse200 = {
  data: GetContestOccurrencesResponse;
  status: 200;
};

export type getContestOccurrencesByContestResponseSuccess =
  getContestOccurrencesByContestResponse200 & {
    headers: Headers;
  };
export type getContestOccurrencesByContestResponse =
  getContestOccurrencesByContestResponseSuccess;

export const getGetContestOccurrencesByContestUrl = (
  contestId: string,
  params: GetContestOccurrencesByContestParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/contests/${contestId}/occurrences?${stringifiedParams}`
    : `/contests/${contestId}/occurrences`;
};

export const getContestOccurrencesByContest = async (
  contestId: string,
  params: GetContestOccurrencesByContestParams,
  options?: RequestInit,
): Promise<getContestOccurrencesByContestResponse> => {
  return api<getContestOccurrencesByContestResponse>(
    getGetContestOccurrencesByContestUrl(contestId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetContestOccurrencesByContestQueryKey = (
  contestId: string,
  params?: GetContestOccurrencesByContestParams,
) => {
  return [
    `/contests/${contestId}/occurrences`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetContestOccurrencesByContestQueryOptions = <
  TData = Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  params: GetContestOccurrencesByContestParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetContestOccurrencesByContestQueryKey(contestId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getContestOccurrencesByContest>>
  > = ({ signal }) =>
    getContestOccurrencesByContest(contestId, params, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!contestId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContestOccurrencesByContestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContestOccurrencesByContest>>
>;
export type GetContestOccurrencesByContestQueryError = ErrorType<unknown>;

export function useGetContestOccurrencesByContest<
  TData = Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  params: GetContestOccurrencesByContestParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
          TError,
          Awaited<ReturnType<typeof getContestOccurrencesByContest>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContestOccurrencesByContest<
  TData = Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  params: GetContestOccurrencesByContestParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
          TError,
          Awaited<ReturnType<typeof getContestOccurrencesByContest>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContestOccurrencesByContest<
  TData = Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  params: GetContestOccurrencesByContestParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Contest Occurrences by Contest
 */

export function useGetContestOccurrencesByContest<
  TData = Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  params: GetContestOccurrencesByContestParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrencesByContest>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContestOccurrencesByContestQueryOptions(
    contestId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create Contest Occurrence
 * @summary Create Contest Occurrence
 */
export type createContestOccurrenceResponse201 = {
  data: void;
  status: 201;
};

export type createContestOccurrenceResponseSuccess =
  createContestOccurrenceResponse201 & {
    headers: Headers;
  };
export type createContestOccurrenceResponse =
  createContestOccurrenceResponseSuccess;

export const getCreateContestOccurrenceUrl = (contestId: string) => {
  return `/contests/${contestId}/occurrences`;
};

export const createContestOccurrence = async (
  contestId: string,
  createContestOccurrenceRequest: CreateContestOccurrenceRequest,
  options?: RequestInit,
): Promise<createContestOccurrenceResponse> => {
  return api<createContestOccurrenceResponse>(
    getCreateContestOccurrenceUrl(contestId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createContestOccurrenceRequest),
    },
  );
};

export const getCreateContestOccurrenceMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createContestOccurrence>>,
    TError,
    { contestId: string; data: CreateContestOccurrenceRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createContestOccurrence>>,
  TError,
  { contestId: string; data: CreateContestOccurrenceRequest },
  TContext
> => {
  const mutationKey = ['createContestOccurrence'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createContestOccurrence>>,
    { contestId: string; data: CreateContestOccurrenceRequest }
  > = (props) => {
    const { contestId, data } = props ?? {};

    return createContestOccurrence(contestId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateContestOccurrenceMutationResult = NonNullable<
  Awaited<ReturnType<typeof createContestOccurrence>>
>;
export type CreateContestOccurrenceMutationBody =
  CreateContestOccurrenceRequest;
export type CreateContestOccurrenceMutationError = ErrorType<unknown>;

/**
 * @summary Create Contest Occurrence
 */
export const useCreateContestOccurrence = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createContestOccurrence>>,
      TError,
      { contestId: string; data: CreateContestOccurrenceRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createContestOccurrence>>,
  TError,
  { contestId: string; data: CreateContestOccurrenceRequest },
  TContext
> => {
  return useMutation(
    getCreateContestOccurrenceMutationOptions(options),
    queryClient,
  );
};
/**
 * Get Contest Occurrence
 * @summary Get Contest Occurrence
 */
export type getContestOccurrenceResponse200 = {
  data: GetContestOccurrenceResponse;
  status: 200;
};

export type getContestOccurrenceResponseSuccess =
  getContestOccurrenceResponse200 & {
    headers: Headers;
  };
export type getContestOccurrenceResponse = getContestOccurrenceResponseSuccess;

export const getGetContestOccurrenceUrl = (
  contestId: string,
  occurrenceId: string,
) => {
  return `/contests/${contestId}/occurrences/${occurrenceId}`;
};

export const getContestOccurrence = async (
  contestId: string,
  occurrenceId: string,
  options?: RequestInit,
): Promise<getContestOccurrenceResponse> => {
  return api<getContestOccurrenceResponse>(
    getGetContestOccurrenceUrl(contestId, occurrenceId),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetContestOccurrenceQueryKey = (
  contestId: string,
  occurrenceId: string,
) => {
  return [`/contests/${contestId}/occurrences/${occurrenceId}`] as const;
};

export const getGetContestOccurrenceQueryOptions = <
  TData = Awaited<ReturnType<typeof getContestOccurrence>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  occurrenceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrence>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetContestOccurrenceQueryKey(contestId, occurrenceId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getContestOccurrence>>
  > = ({ signal }) =>
    getContestOccurrence(contestId, occurrenceId, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!(contestId && occurrenceId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getContestOccurrence>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetContestOccurrenceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getContestOccurrence>>
>;
export type GetContestOccurrenceQueryError = ErrorType<unknown>;

export function useGetContestOccurrence<
  TData = Awaited<ReturnType<typeof getContestOccurrence>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  occurrenceId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrence>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestOccurrence>>,
          TError,
          Awaited<ReturnType<typeof getContestOccurrence>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContestOccurrence<
  TData = Awaited<ReturnType<typeof getContestOccurrence>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  occurrenceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrence>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getContestOccurrence>>,
          TError,
          Awaited<ReturnType<typeof getContestOccurrence>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetContestOccurrence<
  TData = Awaited<ReturnType<typeof getContestOccurrence>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  occurrenceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrence>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Contest Occurrence
 */

export function useGetContestOccurrence<
  TData = Awaited<ReturnType<typeof getContestOccurrence>>,
  TError = ErrorType<unknown>,
>(
  contestId: string,
  occurrenceId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getContestOccurrence>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetContestOccurrenceQueryOptions(
    contestId,
    occurrenceId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
