/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreatePostTemplateRequest,
  CreatePostTemplateResponse,
  GetPostTemplatesResponse,
  UpdatePostTemplateRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getProjectPostTemplatesResponse200 = {
  data: GetPostTemplatesResponse;
  status: 200;
};

export type getProjectPostTemplatesResponseSuccess =
  getProjectPostTemplatesResponse200 & {
    headers: Headers;
  };
export type getProjectPostTemplatesResponse =
  getProjectPostTemplatesResponseSuccess;

export const getGetProjectPostTemplatesUrl = (handle: string) => {
  return `/projects/${handle}/post-templates`;
};

/**
 * 프로젝트의 글 템플릿 목록을 조회합니다. 글을 쓸 수 있는 팀원만 조회할 수 있습니다.
 * @summary Get Project Post Templates
 */
export const getProjectPostTemplates = async (
  handle: string,
  options?: RequestInit,
): Promise<getProjectPostTemplatesResponse> => {
  return api<getProjectPostTemplatesResponse>(
    getGetProjectPostTemplatesUrl(handle),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetProjectPostTemplatesQueryKey = (handle: string) => {
  return [`/projects/${handle}/post-templates`] as const;
};

export const getGetProjectPostTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectPostTemplates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostTemplates>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectPostTemplatesQueryKey(handle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectPostTemplates>>
  > = ({ signal }) =>
    getProjectPostTemplates(handle, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectPostTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectPostTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectPostTemplates>>
>;
export type GetProjectPostTemplatesQueryError = ErrorType<unknown>;

export function useGetProjectPostTemplates<
  TData = Awaited<ReturnType<typeof getProjectPostTemplates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectPostTemplates>>,
          TError,
          Awaited<ReturnType<typeof getProjectPostTemplates>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectPostTemplates<
  TData = Awaited<ReturnType<typeof getProjectPostTemplates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostTemplates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectPostTemplates>>,
          TError,
          Awaited<ReturnType<typeof getProjectPostTemplates>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectPostTemplates<
  TData = Awaited<ReturnType<typeof getProjectPostTemplates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostTemplates>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Post Templates
 */

export function useGetProjectPostTemplates<
  TData = Awaited<ReturnType<typeof getProjectPostTemplates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostTemplates>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectPostTemplatesQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createProjectPostTemplateResponse201 = {
  data: CreatePostTemplateResponse;
  status: 201;
};

export type createProjectPostTemplateResponseSuccess =
  createProjectPostTemplateResponse201 & {
    headers: Headers;
  };
export type createProjectPostTemplateResponse =
  createProjectPostTemplateResponseSuccess;

export const getCreateProjectPostTemplateUrl = (handle: string) => {
  return `/projects/${handle}/post-templates`;
};

/**
 * 프로젝트에 글 템플릿을 생성합니다. 프로젝트 관리자만 생성할 수 있습니다.
 * @summary Create Project Post Template
 */
export const createProjectPostTemplate = async (
  handle: string,
  createPostTemplateRequest?: CreatePostTemplateRequest,
  options?: RequestInit,
): Promise<createProjectPostTemplateResponse> => {
  return api<createProjectPostTemplateResponse>(
    getCreateProjectPostTemplateUrl(handle),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createPostTemplateRequest),
    },
  );
};

export const getCreateProjectPostTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProjectPostTemplate>>,
    TError,
    { handle: string; data?: CreatePostTemplateRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProjectPostTemplate>>,
  TError,
  { handle: string; data?: CreatePostTemplateRequest },
  TContext
> => {
  const mutationKey = ['createProjectPostTemplate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProjectPostTemplate>>,
    { handle: string; data?: CreatePostTemplateRequest }
  > = (props) => {
    const { handle, data } = props ?? {};

    return createProjectPostTemplate(handle, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectPostTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProjectPostTemplate>>
>;
export type CreateProjectPostTemplateMutationBody =
  | CreatePostTemplateRequest
  | undefined;
export type CreateProjectPostTemplateMutationError = ErrorType<unknown>;

/**
 * @summary Create Project Post Template
 */
export const useCreateProjectPostTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProjectPostTemplate>>,
      TError,
      { handle: string; data?: CreatePostTemplateRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProjectPostTemplate>>,
  TError,
  { handle: string; data?: CreatePostTemplateRequest },
  TContext
> => {
  return useMutation(
    getCreateProjectPostTemplateMutationOptions(options),
    queryClient,
  );
};
export type deleteProjectPostTemplateResponse204 = {
  data: void;
  status: 204;
};

export type deleteProjectPostTemplateResponseSuccess =
  deleteProjectPostTemplateResponse204 & {
    headers: Headers;
  };
export type deleteProjectPostTemplateResponse =
  deleteProjectPostTemplateResponseSuccess;

export const getDeleteProjectPostTemplateUrl = (
  handle: string,
  externalId: string,
) => {
  return `/projects/${handle}/post-templates/${externalId}`;
};

/**
 * 프로젝트 글 템플릿을 삭제합니다. 프로젝트 관리자만 삭제할 수 있습니다.
 * @summary Delete Project Post Template
 */
export const deleteProjectPostTemplate = async (
  handle: string,
  externalId: string,
  options?: RequestInit,
): Promise<deleteProjectPostTemplateResponse> => {
  return api<deleteProjectPostTemplateResponse>(
    getDeleteProjectPostTemplateUrl(handle, externalId),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getDeleteProjectPostTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProjectPostTemplate>>,
    TError,
    { handle: string; externalId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProjectPostTemplate>>,
  TError,
  { handle: string; externalId: string },
  TContext
> => {
  const mutationKey = ['deleteProjectPostTemplate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProjectPostTemplate>>,
    { handle: string; externalId: string }
  > = (props) => {
    const { handle, externalId } = props ?? {};

    return deleteProjectPostTemplate(handle, externalId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProjectPostTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProjectPostTemplate>>
>;

export type DeleteProjectPostTemplateMutationError = ErrorType<unknown>;

/**
 * @summary Delete Project Post Template
 */
export const useDeleteProjectPostTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProjectPostTemplate>>,
      TError,
      { handle: string; externalId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProjectPostTemplate>>,
  TError,
  { handle: string; externalId: string },
  TContext
> => {
  return useMutation(
    getDeleteProjectPostTemplateMutationOptions(options),
    queryClient,
  );
};
export type updateProjectPostTemplateResponse204 = {
  data: void;
  status: 204;
};

export type updateProjectPostTemplateResponseSuccess =
  updateProjectPostTemplateResponse204 & {
    headers: Headers;
  };
export type updateProjectPostTemplateResponse =
  updateProjectPostTemplateResponseSuccess;

export const getUpdateProjectPostTemplateUrl = (
  handle: string,
  externalId: string,
) => {
  return `/projects/${handle}/post-templates/${externalId}`;
};

/**
 * 프로젝트 글 템플릿을 수정합니다. 모든 필드를 전체 교체하며, 프로젝트 관리자만 수정할 수 있습니다.
 * @summary Update Project Post Template
 */
export const updateProjectPostTemplate = async (
  handle: string,
  externalId: string,
  updatePostTemplateRequest?: UpdatePostTemplateRequest,
  options?: RequestInit,
): Promise<updateProjectPostTemplateResponse> => {
  return api<updateProjectPostTemplateResponse>(
    getUpdateProjectPostTemplateUrl(handle, externalId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updatePostTemplateRequest),
    },
  );
};

export const getUpdateProjectPostTemplateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProjectPostTemplate>>,
    TError,
    { handle: string; externalId: string; data?: UpdatePostTemplateRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProjectPostTemplate>>,
  TError,
  { handle: string; externalId: string; data?: UpdatePostTemplateRequest },
  TContext
> => {
  const mutationKey = ['updateProjectPostTemplate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProjectPostTemplate>>,
    { handle: string; externalId: string; data?: UpdatePostTemplateRequest }
  > = (props) => {
    const { handle, externalId, data } = props ?? {};

    return updateProjectPostTemplate(handle, externalId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProjectPostTemplateMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProjectPostTemplate>>
>;
export type UpdateProjectPostTemplateMutationBody =
  | UpdatePostTemplateRequest
  | undefined;
export type UpdateProjectPostTemplateMutationError = ErrorType<unknown>;

/**
 * @summary Update Project Post Template
 */
export const useUpdateProjectPostTemplate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProjectPostTemplate>>,
      TError,
      { handle: string; externalId: string; data?: UpdatePostTemplateRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProjectPostTemplate>>,
  TError,
  { handle: string; externalId: string; data?: UpdatePostTemplateRequest },
  TContext
> => {
  return useMutation(
    getUpdateProjectPostTemplateMutationOptions(options),
    queryClient,
  );
};
