#!/usr/bin/env bash

cat <<EOF > apps/web/.env.local
NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_CHANNEL_TALK_PLUGIN_KEY=
NEXT_PUBLIC_CAPTCHA_SITE_KEY=
NEXT_PUBLIC_WEBSOCKET_ENABLED=false
EOF
