/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Type
 */
export type CreateProjectPostRequestType =
  (typeof CreateProjectPostRequestType)[keyof typeof CreateProjectPostRequestType];

export const CreateProjectPostRequestType = {
  Short: 'SHORT',
  Long: 'LONG',
  Question: 'QUESTION',
} as const;
