/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CreateJobPostingRequest {
  /** Job Title */
  jobTitle: string;
  /**
   * Location
   * @nullable
   */
  location?: string | null;
  /** Job Description */
  jobDescription: string;
}
