/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CreateContestOccurrenceRequest {
  /**
   * Contest Occurrence Description
   * @nullable
   */
  description?: string | null;
  /** Contest Occurrence Title */
  title: string;
}
