/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { CreatePostRequestContent } from './CreatePostRequestContent';
import type { CreatePostRequestProject } from './CreatePostRequestProject';
import type { CreatePostRequestStatus } from './CreatePostRequestStatus';
import type { CreatePostRequestTagsItem } from './CreatePostRequestTagsItem';
import type { CreatePostRequestType } from './CreatePostRequestType';

export interface CreatePostRequest {
  /** 프로젝트 */
  project?: CreatePostRequestProject;
  /** Post Type */
  type: CreatePostRequestType;
  /**
   * Title
   * @nullable
   */
  title?: string | null;
  /** Content */
  content: CreatePostRequestContent;
  /**
   * 태그 목록
   * @nullable
   */
  tags?: CreatePostRequestTagsItem[] | null;
  /**
   * Post Status
   * @nullable
   */
  status?: CreatePostRequestStatus;
}
