/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { CreateReflectionRequestContent } from './CreateReflectionRequestContent';
import type { CreateReflectionRequestTagsItem } from './CreateReflectionRequestTagsItem';

export interface CreateReflectionRequest {
  /**
   * Title
   * @nullable
   */
  title?: string | null;
  /**
   * 프로젝트 ID
   * @nullable
   */
  projectId?: number | null;
  /** Content */
  content: CreateReflectionRequestContent;
  /**
   * 태그 목록
   * @nullable
   */
  tags?: CreateReflectionRequestTagsItem[] | null;
}
