/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CreateTagResponse {
  /** 태그 이름 */
  name: string;
  /** 태그가 사용된 게시물 수 */
  postCount: number;
  /** 태그 설명 */
  description: string;
  /** 생성된 태그 ID */
  id: number;
}
