/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 프로젝트
 */
export type CreatePostRequestProject = {
  /**
   * 프로젝트 핸들
   * @nullable
   */
  handle?: string | null;
};
