/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { CreatePostRequestContentMediaIdsItem } from './CreatePostRequestContentMediaIdsItem';

/**
 * Content
 */
export type CreatePostRequestContent = {
  /** JSON Content */
  json: string;
  /**
   * 사용된 미디어 ID 목록
   * @nullable
   */
  mediaIds?: CreatePostRequestContentMediaIdsItem[] | null;
  /** Text Content */
  text: string;
};
