/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CreateJobApplicationRequest {
  /** Company ID */
  companyId: string;
  /** Job Posting ID */
  jobPostingId: string;
}
