/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { CreateReflectionRequestContent } from './CreateReflectionRequestContent';

export interface CreateReflectionRequest {
  /**
   * Title
   * @nullable
   */
  title?: string | null;
  /** Content */
  content: CreateReflectionRequestContent;
}
