/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetBookmarkedPostsResponsePostsNodesItemContentAuthor } from './GetBookmarkedPostsResponsePostsNodesItemContentAuthor';

/**
 * Node Content
 */
export type GetBookmarkedPostsResponsePostsNodesItemContent = {
  /** Created At */
  createdAt: string;
  author?: GetBookmarkedPostsResponsePostsNodesItemContentAuthor;
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** Like Count */
  likeCount: number;
  /** Post ID */
  id: number;
  /** Bookmarked At */
  bookmarkedAt: string;
  /** Content */
  content: string;
  /** Post Slug */
  slug: string;
  /** Comment Count */
  commentCount: number;
};
