/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetBookmarkedPostsResponsePostsNodesItem } from './GetBookmarkedPostsResponsePostsNodesItem';
import type { GetBookmarkedPostsResponsePostsPageInfo } from './GetBookmarkedPostsResponsePostsPageInfo';

export type GetBookmarkedPostsResponsePosts = {
  /** Nodes */
  nodes: GetBookmarkedPostsResponsePostsNodesItem[];
  /** Page Info */
  pageInfo: GetBookmarkedPostsResponsePostsPageInfo;
};
