/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCommentsResponseCommentsItem } from './GetCommentsResponseCommentsItem';

export interface GetCommentsResponse {
  /** Comments */
  comments: GetCommentsResponseCommentsItem[];
}
