/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetConnectionsResponseConnectionsNodesItem } from './GetConnectionsResponseConnectionsNodesItem';
import type { GetConnectionsResponseConnectionsPageInfo } from './GetConnectionsResponseConnectionsPageInfo';

export type GetConnectionsResponseConnections = {
  /** Nodes */
  nodes: GetConnectionsResponseConnectionsNodesItem[];
  /** Page Info */
  pageInfo: GetConnectionsResponseConnectionsPageInfo;
};
