/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCommentsResponseCommentsItemAuthor } from './GetCommentsResponseCommentsItemAuthor';

export type GetCommentsResponseCommentsItem = {
  /** Creation timestamp */
  createdAt: string;
  /** Is deleted */
  isDeleted: boolean;
  author?: GetCommentsResponseCommentsItemAuthor;
  /** Comment ID */
  id: number;
  /**
   * Comment content
   * @nullable
   */
  content?: string | null;
  /** Update timestamp */
  updatedAt: string;
};
