/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCommentsResponseCommentsNodesItemContentRepliesItemAuthor } from './GetCommentsResponseCommentsNodesItemContentRepliesItemAuthor';
import type { GetCommentsResponseCommentsNodesItemContentRepliesItemRepliesItem } from './GetCommentsResponseCommentsNodesItemContentRepliesItemRepliesItem';

export type GetCommentsResponseCommentsNodesItemContentRepliesItem = {
  /** Creation timestamp */
  createdAt: string;
  /** Deleted flag */
  deleted: boolean;
  /** Nested replies */
  replies: GetCommentsResponseCommentsNodesItemContentRepliesItemRepliesItem[];
  author?: GetCommentsResponseCommentsNodesItemContentRepliesItemAuthor;
  /** Reply ID */
  id: number;
  /**
   * Reply content
   * @nullable
   */
  content?: string | null;
  /** Update timestamp */
  updatedAt: string;
};
