/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetContestOccurrencesResponseOccurrencesContentItemContest } from './GetContestOccurrencesResponseOccurrencesContentItemContest';

export type GetContestOccurrencesResponseOccurrencesContentItem = {
  contest?: GetContestOccurrencesResponseOccurrencesContentItemContest;
  /**
   * Occurrence Description
   * @nullable
   */
  description?: string | null;
  /** Contest Occurrence ID */
  id: number;
  /** Occurrence Title */
  title: string;
};
