/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCommentsResponseCommentsNodesItem } from './GetCommentsResponseCommentsNodesItem';
import type { GetCommentsResponseCommentsPageInfo } from './GetCommentsResponseCommentsPageInfo';

export type GetCommentsResponseComments = {
  /** Nodes */
  nodes: GetCommentsResponseCommentsNodesItem[];
  /** Page Info */
  pageInfo: GetCommentsResponseCommentsPageInfo;
};
