/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetCommentedPostsParams = {
  /**
   * Number of items to return from the beginning of the list
   */
  first?: string;
  /**
   * Cursor for pagination, indicating the position after which to return items
   */
  after?: string;
  /**
   * Number of items to return from the end of the list
   */
  last?: string;
  /**
   * Cursor for pagination, indicating the position before which to return items
   */
  before?: string;
  /**
   * 프로젝트 핸들
   */
  projectHandle?: string;
};
