/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCommentsResponseComments } from './GetCommentsResponseComments';

export interface GetCommentsResponse {
  /** Comments */
  comments: GetCommentsResponseComments;
}
