/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetDraftPostsParams = {
  /**
   * Number of items to return from the beginning of the list
   */
  first?: string;
  /**
   * Cursor for pagination, indicating the position after which to return items
   */
  after?: string;
  /**
   * Number of items to return from the end of the list
   */
  last?: string;
  /**
   * Cursor for pagination, indicating the position before which to return items
   */
  before?: string;
  /**
   * 게시글 타입
   */
  type?: string;
  /**
   * 게시글 공개 범위
   */
  scope?: string;
  /**
   * 프로젝트로 검색 범위 제한 (선택)
   */
  projectHandle?: string;
};
