/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetFeedResponseItemsNodesItem } from './GetFeedResponseItemsNodesItem';
import type { GetFeedResponseItemsPageInfo } from './GetFeedResponseItemsPageInfo';

export type GetFeedResponseItems = {
  /** Nodes */
  nodes: GetFeedResponseItemsNodesItem[];
  /** Page Info */
  pageInfo: GetFeedResponseItemsPageInfo;
};
