/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetFeedResponseItemsNodesItemContentAuthor } from './GetFeedResponseItemsNodesItemContentAuthor';

/**
 * Node Content
 */
export type GetFeedResponseItemsNodesItemContent = {
  /** Created At */
  createdAt: string;
  author?: GetFeedResponseItemsNodesItemContentAuthor;
  /** Like Count */
  likeCount: number;
  /** Feed Item ID */
  id: number;
  /** Content */
  content: string;
  /** Comment Count */
  commentCount: number;
};
