/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Page Info
 */
export type GetFollowedTagsResponseTagsPageInfo = {
  /** Page Size */
  size: number;
  /** Has Next Page */
  hasNextPage: boolean;
  /** Has Previous Page */
  hasPreviousPage: boolean;
  /** Page Number */
  page: number;
};
