/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetJobApplicationsResponseApplicationsContentItem } from './GetJobApplicationsResponseApplicationsContentItem';

export type GetJobApplicationsResponseApplications = {
  /** Has Previous */
  hasPrevious: boolean;
  /** Has Next */
  hasNext: boolean;
  /** Content */
  content: GetJobApplicationsResponseApplicationsContentItem[];
};
