/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetJobPostingsResponsePostingsContentItem } from './GetJobPostingsResponsePostingsContentItem';

export type GetJobPostingsResponsePostings = {
  /** Has Previous */
  hasPrevious: boolean;
  /** Has Next */
  hasNext: boolean;
  /** Content */
  content: GetJobPostingsResponsePostingsContentItem[];
};
