/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetJobApplicationResponseCompany } from './GetJobApplicationResponseCompany';
import type { GetJobApplicationResponseJobDescription } from './GetJobApplicationResponseJobDescription';

export interface GetJobApplicationResponse {
  /**
   * Additional Notes
   * @nullable
   */
  notes?: string | null;
  /** Job Description Information */
  jobDescription: GetJobApplicationResponseJobDescription;
  /** Company Information */
  company: GetJobApplicationResponseCompany;
  /** Application ID */
  id: number;
  /** Application Status */
  status: string;
}
