/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetJobPostingResponseCompany } from './GetJobPostingResponseCompany';

export interface GetJobPostingResponse {
  /** Creation Timestamp */
  createdAt: string;
  /** Job Title */
  jobTitle: string;
  /** Location */
  location: string;
  /** Job Description */
  jobDescription: string;
  /** Company */
  company: GetJobPostingResponseCompany;
  /** Job Posting ID */
  id: string;
  /** Update Timestamp */
  updatedAt: string;
}
