/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetMyProjectsResponseProjectsItemJoinPolicy } from './GetMyProjectsResponseProjectsItemJoinPolicy';
import type { GetMyProjectsResponseProjectsItemRole } from './GetMyProjectsResponseProjectsItemRole';

export type GetMyProjectsResponseProjectsItem = {
  /**
   * 프로젝트 웹사이트
   * @nullable
   */
  website?: string | null;
  /** 현재 사용자의 프로젝트 역할 */
  role: GetMyProjectsResponseProjectsItemRole;
  /** 현재 사용자의 프로젝트 소유자 여부 */
  isOwner: boolean;
  /** 프로젝트 멤버 수 */
  memberCount: number;
  /** 프로젝트 이름 */
  name: string;
  /** 공개 여부 */
  isPublic: boolean;
  /**
   * 프로젝트 설명
   * @nullable
   */
  description?: string | null;
  /** 프로젝트 핸들 */
  handle: string;
  /**
   * 프로젝트 아이콘 URL
   * @nullable
   */
  iconUrl?: string | null;
  /** 프로젝트 참여 정책 */
  joinPolicy: GetMyProjectsResponseProjectsItemJoinPolicy;
  /** 공개된 미해결 질문 수 */
  unresolvedQuestionCount: number;
  /** 프로젝트 팔로워 수 */
  followerCount: number;
};
