/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetMyProjectInvitationsResponseInvitationsItemInvitationInviter } from './GetMyProjectInvitationsResponseInvitationsItemInvitationInviter';
import type { GetMyProjectInvitationsResponseInvitationsItemInvitationRole } from './GetMyProjectInvitationsResponseInvitationsItemInvitationRole';

/**
 * 초대 정보
 */
export type GetMyProjectInvitationsResponseInvitationsItemInvitation = {
  /** 초대받은 유저의 역할 */
  role: GetMyProjectInvitationsResponseInvitationsItemInvitationRole;
  /** 초대한 유저 정보 */
  inviter: GetMyProjectInvitationsResponseInvitationsItemInvitationInviter;
  /** 초대 ID */
  id: number;
  /** 초대 만료 시각 */
  expiresAt: string;
};
