/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface GetProjectHandleAvailabilityResponse {
  /** 핸들 사용 가능 여부 */
  available: boolean;
}
