/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetProjectResponseRecentActivitiesItem = {
  /** 활동 내용 */
  text: string;
  /** 활동 ID */
  id: string;
  /** 활동 시각 */
  timestamp: string;
};
