/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProfileResponseContacts } from './GetProfileResponseContacts';

export interface GetProfileResponse {
  /** Profession */
  profession: string;
  /** Is Following */
  isFollowing: boolean;
  /** Role */
  role: string;
  /** Bio */
  bio: string;
  /** Handle */
  handle: string;
  /** ID */
  userId: string;
  /** Is Authenticated User */
  isAuthenticatedUser: boolean;
  /** Is Enabled */
  isEnabled: boolean;
  /** Full Name */
  name: string;
  /** Profile Image URL */
  profileImageUrl: string;
  /** Contacts */
  contacts?: GetProfileResponseContacts;
  /** E-mail */
  email: string;
  /** Is Onboarded */
  isOnboarded: boolean;
}
