/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Type
 */
export type GetPostResponseType =
  (typeof GetPostResponseType)[keyof typeof GetPostResponseType];

export const GetPostResponseType = {
  Short: 'SHORT',
  Long: 'LONG',
  Question: 'QUESTION',
} as const;
