/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsNodesItemContentAuthor } from './GetPostsResponsePostsNodesItemContentAuthor';
import type { GetPostsResponsePostsNodesItemContentProject } from './GetPostsResponsePostsNodesItemContentProject';
import type { GetPostsResponsePostsNodesItemContentType } from './GetPostsResponsePostsNodesItemContentType';

/**
 * Node Content
 */
export type GetPostsResponsePostsNodesItemContent = {
  /** Creation Timestamp */
  createdAt: string;
  author?: GetPostsResponsePostsNodesItemContentAuthor;
  project?: GetPostsResponsePostsNodesItemContentProject;
  /** Post ID */
  id: number;
  /** Post Type */
  type: GetPostsResponsePostsNodesItemContentType;
  /** Post Content */
  content: string;
};
