/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseAuthor } from './GetPostResponseAuthor';
import type { GetPostResponseContent } from './GetPostResponseContent';
import type { GetPostResponseProject } from './GetPostResponseProject';

export interface GetPostResponse {
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** Author Information */
  author: GetPostResponseAuthor;
  /** Project Information */
  project: GetPostResponseProject;
  /** Number of Likes */
  likeCount: number;
  /** Post ID */
  id: number;
  /** Post Content */
  content: GetPostResponseContent;
  /** Post Slug */
  slug: string;
  /** Number of Comments */
  commentCount: number;
}
