/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 소속 프로젝트 정보
 */
export type GetPostsResponsePostsNodesItemContentProject = {
  /**
   * 프로젝트 웹사이트
   * @nullable
   */
  website?: string | null;
  /**
   * 프로젝트 이름
   * @nullable
   */
  name?: string | null;
  /**
   * 공개 여부
   * @nullable
   */
  isPublic?: boolean | null;
  /**
   * 프로젝트 설명
   * @nullable
   */
  description?: string | null;
  /**
   * 프로젝트 핸들
   * @nullable
   */
  handle?: string | null;
  /**
   * 프로젝트 아이콘 URL
   * @nullable
   */
  iconUrl?: string | null;
};
