/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Page Info
 */
export type GetProvidersResponseProvidersPageInfo = {
  /** Page Size */
  size: number;
  /** Has Next Page */
  hasNextPage: boolean;
  /** Has Previous Page */
  hasPreviousPage: boolean;
  /** End Cursor */
  endCursor: string;
  /** Start Cursor */
  startCursor: string;
};
