/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetPostRecommendationsParams = {
  /**
   * Number of items to return from the beginning of the list
   */
  first?: string;
  /**
   * Cursor for pagination, indicating the position after which to return items
   */
  after?: string;
  /**
   * Number of items to return from the end of the list
   */
  last?: string;
  /**
   * Cursor for pagination, indicating the position before which to return items
   */
  before?: string;
  /**
   * 추천 게시글 종류
   */
  type?: string;
  /**
   * 게시글 범위 필터. PUBLIC 은 개인 게시글만, WORKSPACE 는 프로젝트 게시글만 조회한다. 생략하면 두 종류를 모두 포함한다.
   */
  scope?: string;
  /**
   * 게시글 형태 필터. SHORT, LONG, QUESTION 중 하나를 사용한다.
   */
  postType?: string;
};
