/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectExperiencesResponseExperiencesItem } from './GetProjectExperiencesResponseExperiencesItem';

export interface GetProjectExperiencesResponse {
  /** List of project experiences */
  experiences: GetProjectExperiencesResponseExperiencesItem[];
}
