/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Status
 */
export type GetPostRecommendationsResponsePostsNodesItemContentStatus =
  (typeof GetPostRecommendationsResponsePostsNodesItemContentStatus)[keyof typeof GetPostRecommendationsResponsePostsNodesItemContentStatus];

export const GetPostRecommendationsResponsePostsNodesItemContentStatus = {
  Draft: 'DRAFT',
  Published: 'PUBLISHED',
} as const;
