/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostRecommendationsResponsePostsNodesItem } from './GetPostRecommendationsResponsePostsNodesItem';
import type { GetPostRecommendationsResponsePostsPageInfo } from './GetPostRecommendationsResponsePostsPageInfo';

export type GetPostRecommendationsResponsePosts = {
  /** Nodes */
  nodes: GetPostRecommendationsResponsePostsNodesItem[];
  /** Page Info */
  pageInfo: GetPostRecommendationsResponsePostsPageInfo;
};
