/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectsResponseProjectsNodesItemContent } from './GetProjectsResponseProjectsNodesItemContent';

export type GetProjectsResponseProjectsNodesItem = {
  /** Node Cursor */
  cursor: string;
  /** Node Content */
  content: GetProjectsResponseProjectsNodesItemContent;
};
