/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Type
 */
export type GetPostRecommendationsResponsePostsNodesItemContentType =
  (typeof GetPostRecommendationsResponsePostsNodesItemContentType)[keyof typeof GetPostRecommendationsResponsePostsNodesItemContentType];

export const GetPostRecommendationsResponsePostsNodesItemContentType = {
  Short: 'SHORT',
  Long: 'LONG',
  Question: 'QUESTION',
} as const;
