/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectRecommendationsResponseProjectsItem } from './GetProjectRecommendationsResponseProjectsItem';

export interface GetProjectRecommendationsResponse {
  /** 추천 프로젝트 목록 */
  projects: GetProjectRecommendationsResponseProjectsItem[];
}
