/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Type
 */
export type GetPostResponseSummaryType =
  (typeof GetPostResponseSummaryType)[keyof typeof GetPostResponseSummaryType];

export const GetPostResponseSummaryType = {
  Short: 'SHORT',
  Long: 'LONG',
  Question: 'QUESTION',
} as const;
