/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsNodesItemContentAuthor } from './GetPostsResponsePostsNodesItemContentAuthor';
import type { GetPostsResponsePostsNodesItemContentProject } from './GetPostsResponsePostsNodesItemContentProject';

/**
 * Node Content
 */
export type GetPostsResponsePostsNodesItemContent = {
  /** Creation Timestamp */
  createdAt: string;
  author?: GetPostsResponsePostsNodesItemContentAuthor;
  /** Project Information */
  project?: GetPostsResponsePostsNodesItemContentProject;
  /** Post ID */
  id: number;
  /** Post Content */
  content: string;
  /** Post Slug */
  slug: string;
};
