/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectFollowersResponseFollowersNodesItem } from './GetProjectFollowersResponseFollowersNodesItem';
import type { GetProjectFollowersResponseFollowersPageInfo } from './GetProjectFollowersResponseFollowersPageInfo';

export type GetProjectFollowersResponseFollowers = {
  /** Nodes */
  nodes: GetProjectFollowersResponseFollowersNodesItem[];
  /** Page Info */
  pageInfo: GetProjectFollowersResponseFollowersPageInfo;
};
