/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseSummaryAuthor } from './GetPostResponseSummaryAuthor';
import type { GetPostResponseSummaryProject } from './GetPostResponseSummaryProject';
import type { GetPostResponseSummaryStatus } from './GetPostResponseSummaryStatus';
import type { GetPostResponseSummaryType } from './GetPostResponseSummaryType';

/**
 * 포스트 정보
 */
export type GetPostResponseSummary = {
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** 작성자 정보 */
  author: GetPostResponseSummaryAuthor;
  /** 소속 프로젝트 정보 */
  project?: GetPostResponseSummaryProject;
  /** Number of Likes */
  likeCount: number;
  /** Post Type */
  type: GetPostResponseSummaryType;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Whether the current user liked this post */
  liked: boolean;
  /** Number of Comments */
  commentCount: number;
  /** Whether the requesting user is the author of this post */
  isAuthor: boolean;
  /** Creation Timestamp */
  createdAt: string;
  /** Post ID */
  id: number;
  /** Post Slug */
  slug: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
  /** Post Status */
  status: GetPostResponseSummaryStatus;
};
