/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetProjectResponseTeammatesItem = {
  /** 팀원 역할 */
  role: string;
  /** 팀원 이름 */
  name: string;
  /** 팀원 핸들 */
  handle: string;
};
