/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetProjectExperiencesResponseExperiencesItem = {
  /** Experience ID */
  id: number;
  /** Project Name */
  projectName: string;
  /** Project ID */
  projectId: number;
};
