/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectTeammatesResponseTeammatesItemRole } from './GetProjectTeammatesResponseTeammatesItemRole';
import type { GetProjectTeammatesResponseTeammatesItemUser } from './GetProjectTeammatesResponseTeammatesItemUser';

export type GetProjectTeammatesResponseTeammatesItem = {
  /** 팀원 역할 */
  role: GetProjectTeammatesResponseTeammatesItemRole;
  /** 팀원 유저 정보 */
  user: GetProjectTeammatesResponseTeammatesItemUser;
};
