/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 팀원 역할
 */
export type GetProjectResponseTeammatesItemRole =
  (typeof GetProjectResponseTeammatesItemRole)[keyof typeof GetProjectResponseTeammatesItemRole];

export const GetProjectResponseTeammatesItemRole = {
  Admin: 'ADMIN',
  Member: 'MEMBER',
} as const;
