/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectResponseTeammatesItemRole } from './GetProjectResponseTeammatesItemRole';
import type { GetProjectResponseTeammatesItemUser } from './GetProjectResponseTeammatesItemUser';

export type GetProjectResponseTeammatesItem = {
  /** 팀원 역할 */
  role: GetProjectResponseTeammatesItemRole;
  /** 팀원 유저 정보 */
  user: GetProjectResponseTeammatesItemUser;
};
