/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 팀원 역할
 */
export type GetProjectTeammatesResponseTeammatesItemRole =
  (typeof GetProjectTeammatesResponseTeammatesItemRole)[keyof typeof GetProjectTeammatesResponseTeammatesItemRole];

export const GetProjectTeammatesResponseTeammatesItemRole = {
  Admin: 'ADMIN',
  Member: 'MEMBER',
} as const;
