/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 초대받은 유저 정보
 */
export type GetProjectInvitationsResponseInvitationsItemInvitee = {
  /** 유저 이름 */
  name: string;
  /** 유저 핸들 */
  handle: string;
  /**
   * 유저 프로필 이미지 URL
   * @nullable
   */
  profileImageUrl?: string | null;
};
