/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProfileResponseContacts } from './GetProfileResponseContacts';

export interface GetProfileResponse {
  /** Profession */
  profession: string;
  /** Role */
  role: string;
  /** Is Following */
  isFollowing: boolean;
  /** Bio */
  bio: string;
  /**
   * Handle
   * @nullable
   */
  handle?: string | null;
  /** Following Count */
  followingCount: number;
  /** ID */
  userId: string;
  /** Is Authenticated User */
  isAuthenticatedUser: boolean;
  /** Full Name */
  name: string;
  /** Follower Count */
  followerCount: number;
  /** Profile Image URL */
  profileImageUrl: string;
  /** Contacts */
  contacts?: GetProfileResponseContacts;
  /** E-mail */
  email: string;
  /** Is Onboarded */
  isOnboarded: boolean;
}
