/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectResponseRecentActivitiesItem } from './GetProjectResponseRecentActivitiesItem';
import type { GetProjectResponseRole } from './GetProjectResponseRole';
import type { GetProjectResponseTeammatesItem } from './GetProjectResponseTeammatesItem';

export interface GetProjectResponse {
  /** 팀원 목록 */
  teammates: GetProjectResponseTeammatesItem[];
  /**
   * 현재 사용자 역할
   * @nullable
   */
  role?: GetProjectResponseRole;
  /** 최근 활동 목록 */
  recentActivities?: GetProjectResponseRecentActivitiesItem[];
  /** 프로젝트 이름 */
  name: string;
  /** 공개 여부 */
  isPublic: boolean;
  /**
   * 프로젝트 설명
   * @nullable
   */
  description?: string | null;
  /** 프로젝트 핸들 */
  handle: string;
  /** 추가 팀원 존재 여부 */
  hasMoreTeammates: boolean;
}
