/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectResponseRecentActivitiesItem } from './GetProjectResponseRecentActivitiesItem';
import type { GetProjectResponseRole } from './GetProjectResponseRole';
import type { GetProjectResponseSummary } from './GetProjectResponseSummary';
import type { GetProjectResponseTeammatesItem } from './GetProjectResponseTeammatesItem';

export interface GetProjectResponse {
  /** 프로젝트 정보 */
  summary: GetProjectResponseSummary;
  /** 팀원 목록 */
  teammates: GetProjectResponseTeammatesItem[];
  /**
   * 현재 사용자 역할
   * @nullable
   */
  role?: GetProjectResponseRole;
  /** 최근 활동 목록 */
  recentActivities?: GetProjectResponseRecentActivitiesItem[];
  /** 추가 팀원 존재 여부 */
  hasMoreTeammates: boolean;
}
