/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetReflectionsResponseReflectionsContentItem } from './GetReflectionsResponseReflectionsContentItem';

export type GetReflectionsResponseReflections = {
  /**
   * Next Cursor
   * @nullable
   */
  nextCursor?: string | null;
  /** Has Next */
  hasNext: boolean;
  /** Content */
  content: GetReflectionsResponseReflectionsContentItem[];
};
