/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetReflectionResponseAuthor } from './GetReflectionResponseAuthor';

export interface GetReflectionResponse {
  /** Whether the current user bookmarked this reflection */
  bookmarked: boolean;
  /** Author Information */
  author: GetReflectionResponseAuthor;
  /** Number of Likes */
  likeCount: number;
  /** Reflection ID */
  id: number;
  /** Reflection Content */
  content: string;
  /** Reflection Slug */
  slug: string;
  /** Number of Comments */
  commentCount: number;
}
