/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetTeamBuildingPostsResponsePostsContentItemProject } from './GetTeamBuildingPostsResponsePostsContentItemProject';

export type GetTeamBuildingPostsResponsePostsContentItem = {
  /** Project */
  project: GetTeamBuildingPostsResponsePostsContentItemProject;
  /** Post ID */
  id: string;
  /** Post Title */
  title: string;
  /** Post Content */
  content: string;
};
