/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetTagRecommendationsResponseTagsItem } from './GetTagRecommendationsResponseTagsItem';

export interface GetTagRecommendationsResponse {
  /** 태그 목록 */
  tags: GetTagRecommendationsResponseTagsItem[];
}
