/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetUserRecommendationsResponseUsersItem } from './GetUserRecommendationsResponseUsersItem';

export interface GetUserRecommendationsResponse {
  /** 추천 사용자 목록 */
  users: GetUserRecommendationsResponseUsersItem[];
}
