/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type NewLikePayloadType =
  (typeof NewLikePayloadType)[keyof typeof NewLikePayloadType];

export const NewLikePayloadType = {
  NewLike: 'NEW_LIKE',
} as const;
