/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 신고 사유
 */
export type ReportPostRequestReason =
  (typeof ReportPostRequestReason)[keyof typeof ReportPostRequestReason];

export const ReportPostRequestReason = {
  Spam: 'SPAM',
  Harassment: 'HARASSMENT',
  Hate: 'HATE',
  Sexual: 'SEXUAL',
  Violence: 'VIOLENCE',
  Misinformation: 'MISINFORMATION',
  Other: 'OTHER',
} as const;
