/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { ReportPostRequestReason } from './ReportPostRequestReason';

export interface ReportPostRequest {
  /** 신고 사유 */
  reason: ReportPostRequestReason;
  /**
   * 신고 상세 설명
   * @nullable
   */
  description?: string | null;
}
