/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type SearchPostsParams = {
  /**
   * Search query (1-100 characters)
   */
  query: string;
};
