/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type SearchTagsParams = {
  /**
   * 프로젝트 핸들 (지정 시 프로젝트 범위로 검색)
   */
  handle?: string;
  /**
   * 태그 검색어
   */
  query: string;
};
