/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { SearchUsersResponseUsersItem } from './SearchUsersResponseUsersItem';

export interface SearchUsersResponse {
  /** 사용자 목록 */
  users: SearchUsersResponseUsersItem[];
}
