/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type SearchProvidersParams = {
  /**
   * Pagination Cursor
   */
  cursor?: string;
  /**
   * Page Size (Long)
   */
  size: string;
  /**
   * Search Query
   */
  query?: string;
  /**
   * Provider Types List
   */
  types?: string;
};
