/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type SearchPostsParams = {
  /**
   * Search query (1-100 characters)
   */
  query: string;
  /**
   * 프로젝트로 검색 범위 제한 (선택)
   */
  projectHandle?: string;
};
