/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { SearchPostsResponsePostsItemSummary } from './SearchPostsResponsePostsItemSummary';

export type SearchPostsResponsePostsItem = {
  /** Post Summary */
  summary: SearchPostsResponsePostsItemSummary;
  /** Post Content */
  content: string;
};
