/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateProjectPostRequestContent } from './UpdateProjectPostRequestContent';
import type { UpdateProjectPostRequestProjectTagsItem } from './UpdateProjectPostRequestProjectTagsItem';
import type { UpdateProjectPostRequestStatus } from './UpdateProjectPostRequestStatus';
import type { UpdateProjectPostRequestTagsItem } from './UpdateProjectPostRequestTagsItem';
import type { UpdateProjectPostRequestType } from './UpdateProjectPostRequestType';

export interface UpdateProjectPostRequest {
  /**
   * 프로젝트 태그 목록
   * @nullable
   */
  projectTags?: UpdateProjectPostRequestProjectTagsItem[] | null;
  /** Post Type */
  type: UpdateProjectPostRequestType;
  /**
   * Title
   * @nullable
   */
  title?: string | null;
  /** Content */
  content: UpdateProjectPostRequestContent;
  /**
   * 전역 태그 목록
   * @nullable
   */
  tags?: UpdateProjectPostRequestTagsItem[] | null;
  /** Post Status */
  status: UpdateProjectPostRequestStatus;
}
