/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateProfileRequestContacts } from './UpdateProfileRequestContacts';

export interface UpdateProfileRequest {
  /**
   * Profession
   * @nullable
   */
  profession?: string | null;
  /**
   * Profile Image ID
   * @nullable
   */
  profileImageId?: number | null;
  /**
   * Full Name
   * @nullable
   */
  name?: string | null;
  /**
   * Bio
   * @nullable
   */
  bio?: string | null;
  /**
   * Handle
   * @nullable
   */
  handle?: string | null;
  /**
   * Remove Profile Image
   * @nullable
   */
  removeProfileImage?: boolean | null;
  /** Contacts */
  contacts?: UpdateProfileRequestContacts;
  /**
   * Is Onboarded
   * @nullable
   */
  isOnboarded?: boolean | null;
}
