/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface UpdatePostRequest {
  /**
   * Project ID
   * @nullable
   */
  projectId?: number | null;
  /** Content */
  content: string;
}
