/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { UpdatePostRequestContentMediaIdsItem } from './UpdatePostRequestContentMediaIdsItem';

/**
 * Content
 */
export type UpdatePostRequestContent = {
  /** JSON Content */
  json: string;
  /**
   * 사용된 미디어 ID 목록
   * @nullable
   */
  mediaIds?: UpdatePostRequestContentMediaIdsItem[] | null;
  /** Text Content */
  text: string;
};
