/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface UploadMediaResponse {
  /** Pre-signed Upload URL */
  uploadUrl: string;
  /** Media ID */
  mediaId: number;
  /** Expiration Time */
  expiresAt: string;
}
