/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type { GetFeedResponse, GetRecentFeedParams } from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get Recent Feed
 * @summary Get Recent Feed
 */
export type getRecentFeedResponse200 = {
  data: GetFeedResponse;
  status: 200;
};

export type getRecentFeedResponseSuccess = getRecentFeedResponse200 & {
  headers: Headers;
};
export type getRecentFeedResponse = getRecentFeedResponseSuccess;

export const getGetRecentFeedUrl = (params?: GetRecentFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/feed/recent?${stringifiedParams}`
    : `/feed/recent`;
};

export const getRecentFeed = async (
  params?: GetRecentFeedParams,
  options?: RequestInit,
): Promise<getRecentFeedResponse> => {
  return api<getRecentFeedResponse>(getGetRecentFeedUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetRecentFeedInfiniteQueryKey = (
  params?: GetRecentFeedParams,
) => {
  return ['infinite', `/feed/recent`, ...(params ? [params] : [])] as const;
};

export const getGetRecentFeedQueryKey = (params?: GetRecentFeedParams) => {
  return [`/feed/recent`, ...(params ? [params] : [])] as const;
};

export const getGetRecentFeedInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecentFeed>>,
    GetRecentFeedParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentFeed>>,
        TError,
        TData,
        QueryKey,
        GetRecentFeedParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRecentFeedInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecentFeed>>,
    QueryKey,
    GetRecentFeedParams['after']
  > = ({ signal, pageParam }) =>
    getRecentFeed(
      { ...params, after: pageParam || params?.['after'] },
      { signal, ...requestOptions },
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getRecentFeed>>,
    TError,
    TData,
    QueryKey,
    GetRecentFeedParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecentFeedInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentFeed>>
>;
export type GetRecentFeedInfiniteQueryError = ErrorType<unknown>;

export function useGetRecentFeedInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecentFeed>>,
    GetRecentFeedParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetRecentFeedParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentFeed>>,
        TError,
        TData,
        QueryKey,
        GetRecentFeedParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeed>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeed>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeedInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecentFeed>>,
    GetRecentFeedParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentFeed>>,
        TError,
        TData,
        QueryKey,
        GetRecentFeedParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeed>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeed>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeedInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecentFeed>>,
    GetRecentFeedParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentFeed>>,
        TError,
        TData,
        QueryKey,
        GetRecentFeedParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Recent Feed
 */

export function useGetRecentFeedInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecentFeed>>,
    GetRecentFeedParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecentFeed>>,
        TError,
        TData,
        QueryKey,
        GetRecentFeedParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecentFeedInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetRecentFeedQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecentFeed>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeed>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecentFeedQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecentFeed>>> = ({
    signal,
  }) => getRecentFeed(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecentFeed>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecentFeedQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecentFeed>>
>;
export type GetRecentFeedQueryError = ErrorType<unknown>;

export function useGetRecentFeed<
  TData = Awaited<ReturnType<typeof getRecentFeed>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetRecentFeedParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeed>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeed>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeed>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeed<
  TData = Awaited<ReturnType<typeof getRecentFeed>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeed>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecentFeed>>,
          TError,
          Awaited<ReturnType<typeof getRecentFeed>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecentFeed<
  TData = Awaited<ReturnType<typeof getRecentFeed>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeed>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Recent Feed
 */

export function useGetRecentFeed<
  TData = Awaited<ReturnType<typeof getRecentFeed>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecentFeedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRecentFeed>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecentFeedQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
