spring:
  application:
    name: sync

  config:
    import: optional:file:.env[.properties]

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
