/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreateJobApplicationRequest,
  CreateJobApplicationResponse,
  GetJobApplicationsResponse,
  GetMyJobApplicationsParams,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Create Job Application
 * @summary Create Job Application
 */
export type createJobApplicationResponse201 = {
  data: CreateJobApplicationResponse;
  status: 201;
};

export type createJobApplicationResponseSuccess =
  createJobApplicationResponse201 & {
    headers: Headers;
  };
export type createJobApplicationResponse = createJobApplicationResponseSuccess;

export const getCreateJobApplicationUrl = () => {
  return `/applications`;
};

export const createJobApplication = async (
  createJobApplicationRequest: CreateJobApplicationRequest,
  options?: RequestInit,
): Promise<createJobApplicationResponse> => {
  return api<createJobApplicationResponse>(getCreateJobApplicationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createJobApplicationRequest),
  });
};

export const getCreateJobApplicationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createJobApplication>>,
    TError,
    { data: CreateJobApplicationRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createJobApplication>>,
  TError,
  { data: CreateJobApplicationRequest },
  TContext
> => {
  const mutationKey = ['createJobApplication'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createJobApplication>>,
    { data: CreateJobApplicationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createJobApplication(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateJobApplicationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createJobApplication>>
>;
export type CreateJobApplicationMutationBody = CreateJobApplicationRequest;
export type CreateJobApplicationMutationError = ErrorType<unknown>;

/**
 * @summary Create Job Application
 */
export const useCreateJobApplication = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createJobApplication>>,
      TError,
      { data: CreateJobApplicationRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createJobApplication>>,
  TError,
  { data: CreateJobApplicationRequest },
  TContext
> => {
  return useMutation(
    getCreateJobApplicationMutationOptions(options),
    queryClient,
  );
};
/**
 * Get My Job Applications
 * @summary Get My Job Applications
 */
export type getMyJobApplicationsResponse200 = {
  data: GetJobApplicationsResponse;
  status: 200;
};

export type getMyJobApplicationsResponseSuccess =
  getMyJobApplicationsResponse200 & {
    headers: Headers;
  };
export type getMyJobApplicationsResponse = getMyJobApplicationsResponseSuccess;

export const getGetMyJobApplicationsUrl = (
  params: GetMyJobApplicationsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/applications/me?${stringifiedParams}`
    : `/applications/me`;
};

export const getMyJobApplications = async (
  params: GetMyJobApplicationsParams,
  options?: RequestInit,
): Promise<getMyJobApplicationsResponse> => {
  return api<getMyJobApplicationsResponse>(getGetMyJobApplicationsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetMyJobApplicationsQueryKey = (
  params?: GetMyJobApplicationsParams,
) => {
  return [`/applications/me`, ...(params ? [params] : [])] as const;
};

export const getGetMyJobApplicationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMyJobApplicationsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyJobApplications>>
  > = ({ signal }) =>
    getMyJobApplications(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyJobApplications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyJobApplicationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyJobApplications>>
>;
export type GetMyJobApplicationsQueryError = ErrorType<unknown>;

export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyJobApplications>>,
          TError,
          Awaited<ReturnType<typeof getMyJobApplications>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyJobApplications>>,
          TError,
          Awaited<ReturnType<typeof getMyJobApplications>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get My Job Applications
 */

export function useGetMyJobApplications<
  TData = Awaited<ReturnType<typeof getMyJobApplications>>,
  TError = ErrorType<unknown>,
>(
  params: GetMyJobApplicationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyJobApplications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyJobApplicationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
