/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type { GetProjectsResponse, GetTrendingProjectsParams } from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get Trending Projects
 * @summary Get Trending Projects
 */
export type getTrendingProjectsResponse200 = {
  data: GetProjectsResponse;
  status: 200;
};

export type getTrendingProjectsResponseSuccess =
  getTrendingProjectsResponse200 & {
    headers: Headers;
  };
export type getTrendingProjectsResponse = getTrendingProjectsResponseSuccess;

export const getGetTrendingProjectsUrl = (
  params?: GetTrendingProjectsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/projects/trending?${stringifiedParams}`
    : `/projects/trending`;
};

export const getTrendingProjects = async (
  params?: GetTrendingProjectsParams,
  options?: RequestInit,
): Promise<getTrendingProjectsResponse> => {
  return api<getTrendingProjectsResponse>(getGetTrendingProjectsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetTrendingProjectsInfiniteQueryKey = (
  params?: GetTrendingProjectsParams,
) => {
  return [
    'infinite',
    `/projects/trending`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetTrendingProjectsQueryKey = (
  params?: GetTrendingProjectsParams,
) => {
  return [`/projects/trending`, ...(params ? [params] : [])] as const;
};

export const getGetTrendingProjectsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    GetTrendingProjectsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData,
        QueryKey,
        GetTrendingProjectsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTrendingProjectsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    QueryKey,
    GetTrendingProjectsParams['after']
  > = ({ signal, pageParam }) =>
    getTrendingProjects(
      { ...params, after: pageParam || params?.['after'] },
      { signal, ...requestOptions },
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    TError,
    TData,
    QueryKey,
    GetTrendingProjectsParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTrendingProjectsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrendingProjects>>
>;
export type GetTrendingProjectsInfiniteQueryError = ErrorType<unknown>;

export function useGetTrendingProjectsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    GetTrendingProjectsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetTrendingProjectsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData,
        QueryKey,
        GetTrendingProjectsParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrendingProjects>>,
          TError,
          Awaited<ReturnType<typeof getTrendingProjects>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrendingProjectsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    GetTrendingProjectsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData,
        QueryKey,
        GetTrendingProjectsParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrendingProjects>>,
          TError,
          Awaited<ReturnType<typeof getTrendingProjects>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrendingProjectsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    GetTrendingProjectsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData,
        QueryKey,
        GetTrendingProjectsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Trending Projects
 */

export function useGetTrendingProjectsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    GetTrendingProjectsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData,
        QueryKey,
        GetTrendingProjectsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTrendingProjectsInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetTrendingProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrendingProjects>>,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTrendingProjectsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTrendingProjects>>
  > = ({ signal }) =>
    getTrendingProjects(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTrendingProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTrendingProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrendingProjects>>
>;
export type GetTrendingProjectsQueryError = ErrorType<unknown>;

export function useGetTrendingProjects<
  TData = Awaited<ReturnType<typeof getTrendingProjects>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetTrendingProjectsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrendingProjects>>,
          TError,
          Awaited<ReturnType<typeof getTrendingProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrendingProjects<
  TData = Awaited<ReturnType<typeof getTrendingProjects>>,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrendingProjects>>,
          TError,
          Awaited<ReturnType<typeof getTrendingProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTrendingProjects<
  TData = Awaited<ReturnType<typeof getTrendingProjects>>,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Trending Projects
 */

export function useGetTrendingProjects<
  TData = Awaited<ReturnType<typeof getTrendingProjects>>,
  TError = ErrorType<unknown>,
>(
  params?: GetTrendingProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTrendingProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTrendingProjectsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
