/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  AddTeammateRequest,
  CreateProjectInvitationRequest,
  CreateProjectRequest,
  CreateProjectResponse,
  GetMyProjectInvitationsResponse,
  GetProjectFollowersParams,
  GetProjectFollowersResponse,
  GetProjectHandleAvailabilityParams,
  GetProjectHandleAvailabilityResponse,
  GetProjectInvitationsResponse,
  GetProjectRecommendationsParams,
  GetProjectRecommendationsResponse,
  GetProjectResponse,
  GetProjectTeammatesResponse,
  GetProjectsResponse,
  SearchMyProjectsParams,
  SearchProjectsParams,
  UpdateProjectRequest,
  UpdateTeammateRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getMyProjectInvitationsResponse200 = {
  data: GetMyProjectInvitationsResponse;
  status: 200;
};

export type getMyProjectInvitationsResponseSuccess =
  getMyProjectInvitationsResponse200 & {
    headers: Headers;
  };
export type getMyProjectInvitationsResponse =
  getMyProjectInvitationsResponseSuccess;

export const getGetMyProjectInvitationsUrl = () => {
  return `/invitations`;
};

/**
 * 내가 받은 대기 중인 프로젝트 초대 목록을 조회합니다.
 * @summary Get My Project Invitations
 */
export const getMyProjectInvitations = async (
  options?: RequestInit,
): Promise<getMyProjectInvitationsResponse> => {
  return api<getMyProjectInvitationsResponse>(getGetMyProjectInvitationsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetMyProjectInvitationsQueryKey = () => {
  return [`/invitations`] as const;
};

export const getGetMyProjectInvitationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyProjectInvitations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getMyProjectInvitations>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMyProjectInvitationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMyProjectInvitations>>
  > = ({ signal }) => getMyProjectInvitations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyProjectInvitations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyProjectInvitationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyProjectInvitations>>
>;
export type GetMyProjectInvitationsQueryError = ErrorType<unknown>;

export function useGetMyProjectInvitations<
  TData = Awaited<ReturnType<typeof getMyProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyProjectInvitations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProjectInvitations>>,
          TError,
          Awaited<ReturnType<typeof getMyProjectInvitations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyProjectInvitations<
  TData = Awaited<ReturnType<typeof getMyProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyProjectInvitations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyProjectInvitations>>,
          TError,
          Awaited<ReturnType<typeof getMyProjectInvitations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyProjectInvitations<
  TData = Awaited<ReturnType<typeof getMyProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyProjectInvitations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get My Project Invitations
 */

export function useGetMyProjectInvitations<
  TData = Awaited<ReturnType<typeof getMyProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyProjectInvitations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyProjectInvitationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type acceptProjectInvitationResponse204 = {
  data: void;
  status: 204;
};

export type acceptProjectInvitationResponseSuccess =
  acceptProjectInvitationResponse204 & {
    headers: Headers;
  };
export type acceptProjectInvitationResponse =
  acceptProjectInvitationResponseSuccess;

export const getAcceptProjectInvitationUrl = (token: string) => {
  return `/invitations/${token}/accept`;
};

/**
 * 프로젝트 초대를 수락합니다.
 * @summary Accept Project Invitation
 */
export const acceptProjectInvitation = async (
  token: string,
  options?: RequestInit,
): Promise<acceptProjectInvitationResponse> => {
  return api<acceptProjectInvitationResponse>(
    getAcceptProjectInvitationUrl(token),
    {
      ...options,
      method: 'POST',
    },
  );
};

export const getAcceptProjectInvitationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acceptProjectInvitation>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acceptProjectInvitation>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationKey = ['acceptProjectInvitation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acceptProjectInvitation>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return acceptProjectInvitation(token, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcceptProjectInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof acceptProjectInvitation>>
>;

export type AcceptProjectInvitationMutationError = ErrorType<unknown>;

/**
 * @summary Accept Project Invitation
 */
export const useAcceptProjectInvitation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof acceptProjectInvitation>>,
      TError,
      { token: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof acceptProjectInvitation>>,
  TError,
  { token: string },
  TContext
> => {
  return useMutation(
    getAcceptProjectInvitationMutationOptions(options),
    queryClient,
  );
};
export type declineProjectInvitationResponse204 = {
  data: void;
  status: 204;
};

export type declineProjectInvitationResponseSuccess =
  declineProjectInvitationResponse204 & {
    headers: Headers;
  };
export type declineProjectInvitationResponse =
  declineProjectInvitationResponseSuccess;

export const getDeclineProjectInvitationUrl = (token: string) => {
  return `/invitations/${token}/decline`;
};

/**
 * 프로젝트 초대를 거절합니다.
 * @summary Decline Project Invitation
 */
export const declineProjectInvitation = async (
  token: string,
  options?: RequestInit,
): Promise<declineProjectInvitationResponse> => {
  return api<declineProjectInvitationResponse>(
    getDeclineProjectInvitationUrl(token),
    {
      ...options,
      method: 'POST',
    },
  );
};

export const getDeclineProjectInvitationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof declineProjectInvitation>>,
    TError,
    { token: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof declineProjectInvitation>>,
  TError,
  { token: string },
  TContext
> => {
  const mutationKey = ['declineProjectInvitation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof declineProjectInvitation>>,
    { token: string }
  > = (props) => {
    const { token } = props ?? {};

    return declineProjectInvitation(token, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeclineProjectInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof declineProjectInvitation>>
>;

export type DeclineProjectInvitationMutationError = ErrorType<unknown>;

/**
 * @summary Decline Project Invitation
 */
export const useDeclineProjectInvitation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof declineProjectInvitation>>,
      TError,
      { token: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof declineProjectInvitation>>,
  TError,
  { token: string },
  TContext
> => {
  return useMutation(
    getDeclineProjectInvitationMutationOptions(options),
    queryClient,
  );
};
export type createProjectResponse201 = {
  data: CreateProjectResponse;
  status: 201;
};

export type createProjectResponseSuccess = createProjectResponse201 & {
  headers: Headers;
};
export type createProjectResponse = createProjectResponseSuccess;

export const getCreateProjectUrl = () => {
  return `/projects`;
};

/**
 * 새로운 프로젝트를 생성합니다.
 * @summary Create Project
 */
export const createProject = async (
  createProjectRequest?: CreateProjectRequest,
  options?: RequestInit,
): Promise<createProjectResponse> => {
  return api<createProjectResponse>(getCreateProjectUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json;charset=UTF-8',
      ...options?.headers,
    },
    body: JSON.stringify(createProjectRequest),
  });
};

export const getCreateProjectMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProject>>,
    TError,
    { data?: CreateProjectRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data?: CreateProjectRequest },
  TContext
> => {
  const mutationKey = ['createProject'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProject>>,
    { data?: CreateProjectRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createProject(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProject>>
>;
export type CreateProjectMutationBody = CreateProjectRequest | undefined;
export type CreateProjectMutationError = ErrorType<unknown>;

/**
 * @summary Create Project
 */
export const useCreateProject = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProject>>,
      TError,
      { data?: CreateProjectRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data?: CreateProjectRequest },
  TContext
> => {
  return useMutation(getCreateProjectMutationOptions(options), queryClient);
};
export type getProjectRecommendationsResponse200 = {
  data: GetProjectRecommendationsResponse;
  status: 200;
};

export type getProjectRecommendationsResponseSuccess =
  getProjectRecommendationsResponse200 & {
    headers: Headers;
  };
export type getProjectRecommendationsResponse =
  getProjectRecommendationsResponseSuccess;

export const getGetProjectRecommendationsUrl = (
  params?: GetProjectRecommendationsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/projects/recommendations?${stringifiedParams}`
    : `/projects/recommendations`;
};

/**
 * 팔로우할 만한 프로젝트 목록을 추천합니다.
 * @summary Get Project Recommendations
 */
export const getProjectRecommendations = async (
  params?: GetProjectRecommendationsParams,
  options?: RequestInit,
): Promise<getProjectRecommendationsResponse> => {
  return api<getProjectRecommendationsResponse>(
    getGetProjectRecommendationsUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetProjectRecommendationsQueryKey = (
  params?: GetProjectRecommendationsParams,
) => {
  return [`/projects/recommendations`, ...(params ? [params] : [])] as const;
};

export const getGetProjectRecommendationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProjectRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectRecommendations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectRecommendationsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectRecommendations>>
  > = ({ signal }) =>
    getProjectRecommendations(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectRecommendations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectRecommendationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectRecommendations>>
>;
export type GetProjectRecommendationsQueryError = ErrorType<unknown>;

export function useGetProjectRecommendations<
  TData = Awaited<ReturnType<typeof getProjectRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetProjectRecommendationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectRecommendations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getProjectRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectRecommendations<
  TData = Awaited<ReturnType<typeof getProjectRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProjectRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectRecommendations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getProjectRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectRecommendations<
  TData = Awaited<ReturnType<typeof getProjectRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProjectRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectRecommendations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Recommendations
 */

export function useGetProjectRecommendations<
  TData = Awaited<ReturnType<typeof getProjectRecommendations>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProjectRecommendationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectRecommendations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectRecommendationsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProjectByHandleResponse200 = {
  data: GetProjectResponse;
  status: 200;
};

export type getProjectByHandleResponseSuccess =
  getProjectByHandleResponse200 & {
    headers: Headers;
  };
export type getProjectByHandleResponse = getProjectByHandleResponseSuccess;

export const getGetProjectByHandleUrl = (handle: string) => {
  return `/projects/${handle}`;
};

/**
 * 핸들로 프로젝트를 조회합니다.
 * @summary Get Project By Handle
 */
export const getProjectByHandle = async (
  handle: string,
  options?: RequestInit,
): Promise<getProjectByHandleResponse> => {
  return api<getProjectByHandleResponse>(getGetProjectByHandleUrl(handle), {
    ...options,
    method: 'GET',
  });
};

export const getGetProjectByHandleQueryKey = (handle: string) => {
  return [`/projects/${handle}`] as const;
};

export const getGetProjectByHandleQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectByHandle>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectByHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectByHandleQueryKey(handle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectByHandle>>
  > = ({ signal }) => getProjectByHandle(handle, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectByHandle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectByHandleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectByHandle>>
>;
export type GetProjectByHandleQueryError = ErrorType<unknown>;

export function useGetProjectByHandle<
  TData = Awaited<ReturnType<typeof getProjectByHandle>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectByHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectByHandle>>,
          TError,
          Awaited<ReturnType<typeof getProjectByHandle>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectByHandle<
  TData = Awaited<ReturnType<typeof getProjectByHandle>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectByHandle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectByHandle>>,
          TError,
          Awaited<ReturnType<typeof getProjectByHandle>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectByHandle<
  TData = Awaited<ReturnType<typeof getProjectByHandle>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectByHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project By Handle
 */

export function useGetProjectByHandle<
  TData = Awaited<ReturnType<typeof getProjectByHandle>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectByHandle>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectByHandleQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type updateProjectResponse204 = {
  data: void;
  status: 204;
};

export type updateProjectResponseSuccess = updateProjectResponse204 & {
  headers: Headers;
};
export type updateProjectResponse = updateProjectResponseSuccess;

export const getUpdateProjectUrl = (handle: string) => {
  return `/projects/${handle}`;
};

/**
 * 프로젝트 정보를 수정합니다.
 * @summary Update Project
 */
export const updateProject = async (
  handle: string,
  updateProjectRequest?: UpdateProjectRequest,
  options?: RequestInit,
): Promise<updateProjectResponse> => {
  return api<updateProjectResponse>(getUpdateProjectUrl(handle), {
    ...options,
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json;charset=UTF-8',
      ...options?.headers,
    },
    body: JSON.stringify(updateProjectRequest),
  });
};

export const getUpdateProjectMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProject>>,
    TError,
    { handle: string; data?: UpdateProjectRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProject>>,
  TError,
  { handle: string; data?: UpdateProjectRequest },
  TContext
> => {
  const mutationKey = ['updateProject'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProject>>,
    { handle: string; data?: UpdateProjectRequest }
  > = (props) => {
    const { handle, data } = props ?? {};

    return updateProject(handle, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProject>>
>;
export type UpdateProjectMutationBody = UpdateProjectRequest | undefined;
export type UpdateProjectMutationError = ErrorType<unknown>;

/**
 * @summary Update Project
 */
export const useUpdateProject = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProject>>,
      TError,
      { handle: string; data?: UpdateProjectRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProject>>,
  TError,
  { handle: string; data?: UpdateProjectRequest },
  TContext
> => {
  return useMutation(getUpdateProjectMutationOptions(options), queryClient);
};
export type getProjectHandleAvailabilityResponse200 = {
  data: GetProjectHandleAvailabilityResponse;
  status: 200;
};

export type getProjectHandleAvailabilityResponseSuccess =
  getProjectHandleAvailabilityResponse200 & {
    headers: Headers;
  };
export type getProjectHandleAvailabilityResponse =
  getProjectHandleAvailabilityResponseSuccess;

export const getGetProjectHandleAvailabilityUrl = (
  params: GetProjectHandleAvailabilityParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/projects/handles/availability?${stringifiedParams}`
    : `/projects/handles/availability`;
};

/**
 * 프로젝트 핸들의 사용 가능 여부를 확인합니다.
 * @summary Get Project Handle Availability
 */
export const getProjectHandleAvailability = async (
  params: GetProjectHandleAvailabilityParams,
  options?: RequestInit,
): Promise<getProjectHandleAvailabilityResponse> => {
  return api<getProjectHandleAvailabilityResponse>(
    getGetProjectHandleAvailabilityUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetProjectHandleAvailabilityQueryKey = (
  params?: GetProjectHandleAvailabilityParams,
) => {
  return [
    `/projects/handles/availability`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetProjectHandleAvailabilityQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetProjectHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectHandleAvailability>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectHandleAvailabilityQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectHandleAvailability>>
  > = ({ signal }) =>
    getProjectHandleAvailability(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectHandleAvailability>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectHandleAvailabilityQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectHandleAvailability>>
>;
export type GetProjectHandleAvailabilityQueryError = ErrorType<unknown>;

export function useGetProjectHandleAvailability<
  TData = Awaited<ReturnType<typeof getProjectHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetProjectHandleAvailabilityParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectHandleAvailability>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectHandleAvailability>>,
          TError,
          Awaited<ReturnType<typeof getProjectHandleAvailability>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectHandleAvailability<
  TData = Awaited<ReturnType<typeof getProjectHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetProjectHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectHandleAvailability>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectHandleAvailability>>,
          TError,
          Awaited<ReturnType<typeof getProjectHandleAvailability>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectHandleAvailability<
  TData = Awaited<ReturnType<typeof getProjectHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetProjectHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectHandleAvailability>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Handle Availability
 */

export function useGetProjectHandleAvailability<
  TData = Awaited<ReturnType<typeof getProjectHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetProjectHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectHandleAvailability>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectHandleAvailabilityQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type followProjectResponse200 = {
  data: void;
  status: 200;
};

export type followProjectResponseSuccess = followProjectResponse200 & {
  headers: Headers;
};
export type followProjectResponse = followProjectResponseSuccess;

export const getFollowProjectUrl = (handle: string) => {
  return `/projects/${handle}/follow`;
};

/**
 * 프로젝트를 팔로우합니다.
 * @summary Follow Project
 */
export const followProject = async (
  handle: string,
  options?: RequestInit,
): Promise<followProjectResponse> => {
  return api<followProjectResponse>(getFollowProjectUrl(handle), {
    ...options,
    method: 'POST',
  });
};

export const getFollowProjectMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof followProject>>,
    TError,
    { handle: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof followProject>>,
  TError,
  { handle: string },
  TContext
> => {
  const mutationKey = ['followProject'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof followProject>>,
    { handle: string }
  > = (props) => {
    const { handle } = props ?? {};

    return followProject(handle, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FollowProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof followProject>>
>;

export type FollowProjectMutationError = ErrorType<unknown>;

/**
 * @summary Follow Project
 */
export const useFollowProject = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof followProject>>,
      TError,
      { handle: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof followProject>>,
  TError,
  { handle: string },
  TContext
> => {
  return useMutation(getFollowProjectMutationOptions(options), queryClient);
};
export type getProjectFollowersResponse200 = {
  data: GetProjectFollowersResponse;
  status: 200;
};

export type getProjectFollowersResponseSuccess =
  getProjectFollowersResponse200 & {
    headers: Headers;
  };
export type getProjectFollowersResponse = getProjectFollowersResponseSuccess;

export const getGetProjectFollowersUrl = (
  handle: string,
  params?: GetProjectFollowersParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/projects/${handle}/followers?${stringifiedParams}`
    : `/projects/${handle}/followers`;
};

/**
 * 프로젝트를 팔로우하는 사용자 목록을 조회합니다.
 * @summary Get Project Followers
 */
export const getProjectFollowers = async (
  handle: string,
  params?: GetProjectFollowersParams,
  options?: RequestInit,
): Promise<getProjectFollowersResponse> => {
  return api<getProjectFollowersResponse>(
    getGetProjectFollowersUrl(handle, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetProjectFollowersInfiniteQueryKey = (
  handle: string,
  params?: GetProjectFollowersParams,
) => {
  return [
    'infinite',
    `/projects/${handle}/followers`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetProjectFollowersQueryKey = (
  handle: string,
  params?: GetProjectFollowersParams,
) => {
  return [
    `/projects/${handle}/followers`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetProjectFollowersInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    GetProjectFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData,
        QueryKey,
        GetProjectFollowersParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetProjectFollowersInfiniteQueryKey(handle, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    QueryKey,
    GetProjectFollowersParams['after']
  > = ({ signal, pageParam }) =>
    getProjectFollowers(
      handle,
      { ...params, after: pageParam ?? params?.['after'] },
      { signal, ...requestOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    TError,
    TData,
    QueryKey,
    GetProjectFollowersParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectFollowersInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectFollowers>>
>;
export type GetProjectFollowersInfiniteQueryError = ErrorType<unknown>;

export function useGetProjectFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    GetProjectFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: undefined | GetProjectFollowersParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData,
        QueryKey,
        GetProjectFollowersParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectFollowers>>,
          TError,
          Awaited<ReturnType<typeof getProjectFollowers>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    GetProjectFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData,
        QueryKey,
        GetProjectFollowersParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectFollowers>>,
          TError,
          Awaited<ReturnType<typeof getProjectFollowers>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    GetProjectFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData,
        QueryKey,
        GetProjectFollowersParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Followers
 */

export function useGetProjectFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    GetProjectFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData,
        QueryKey,
        GetProjectFollowersParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectFollowersInfiniteQueryOptions(
    handle,
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetProjectFollowersQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectFollowers>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectFollowersQueryKey(handle, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectFollowers>>
  > = ({ signal }) =>
    getProjectFollowers(handle, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectFollowers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectFollowersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectFollowers>>
>;
export type GetProjectFollowersQueryError = ErrorType<unknown>;

export function useGetProjectFollowers<
  TData = Awaited<ReturnType<typeof getProjectFollowers>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: undefined | GetProjectFollowersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectFollowers>>,
          TError,
          Awaited<ReturnType<typeof getProjectFollowers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectFollowers<
  TData = Awaited<ReturnType<typeof getProjectFollowers>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectFollowers>>,
          TError,
          Awaited<ReturnType<typeof getProjectFollowers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectFollowers<
  TData = Awaited<ReturnType<typeof getProjectFollowers>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Followers
 */

export function useGetProjectFollowers<
  TData = Awaited<ReturnType<typeof getProjectFollowers>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectFollowers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectFollowersQueryOptions(
    handle,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProjectInvitationsResponse200 = {
  data: GetProjectInvitationsResponse;
  status: 200;
};

export type getProjectInvitationsResponseSuccess =
  getProjectInvitationsResponse200 & {
    headers: Headers;
  };
export type getProjectInvitationsResponse =
  getProjectInvitationsResponseSuccess;

export const getGetProjectInvitationsUrl = (handle: string) => {
  return `/projects/${handle}/invitations`;
};

/**
 * 프로젝트의 대기 중인 초대 목록을 조회합니다.
 * @summary Get Project Invitations
 */
export const getProjectInvitations = async (
  handle: string,
  options?: RequestInit,
): Promise<getProjectInvitationsResponse> => {
  return api<getProjectInvitationsResponse>(
    getGetProjectInvitationsUrl(handle),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetProjectInvitationsQueryKey = (handle: string) => {
  return [`/projects/${handle}/invitations`] as const;
};

export const getGetProjectInvitationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectInvitations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectInvitationsQueryKey(handle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectInvitations>>
  > = ({ signal }) =>
    getProjectInvitations(handle, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectInvitations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectInvitationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectInvitations>>
>;
export type GetProjectInvitationsQueryError = ErrorType<unknown>;

export function useGetProjectInvitations<
  TData = Awaited<ReturnType<typeof getProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectInvitations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectInvitations>>,
          TError,
          Awaited<ReturnType<typeof getProjectInvitations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectInvitations<
  TData = Awaited<ReturnType<typeof getProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectInvitations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectInvitations>>,
          TError,
          Awaited<ReturnType<typeof getProjectInvitations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectInvitations<
  TData = Awaited<ReturnType<typeof getProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectInvitations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Invitations
 */

export function useGetProjectInvitations<
  TData = Awaited<ReturnType<typeof getProjectInvitations>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectInvitations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectInvitationsQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createProjectInvitationResponse201 = {
  data: void;
  status: 201;
};

export type createProjectInvitationResponseSuccess =
  createProjectInvitationResponse201 & {
    headers: Headers;
  };
export type createProjectInvitationResponse =
  createProjectInvitationResponseSuccess;

export const getCreateProjectInvitationUrl = (handle: string) => {
  return `/projects/${handle}/invitations`;
};

/**
 * 프로젝트에 팀원을 초대합니다.
 * @summary Create Project Invitation
 */
export const createProjectInvitation = async (
  handle: string,
  createProjectInvitationRequest?: CreateProjectInvitationRequest,
  options?: RequestInit,
): Promise<createProjectInvitationResponse> => {
  return api<createProjectInvitationResponse>(
    getCreateProjectInvitationUrl(handle),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createProjectInvitationRequest),
    },
  );
};

export const getCreateProjectInvitationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProjectInvitation>>,
    TError,
    { handle: string; data?: CreateProjectInvitationRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProjectInvitation>>,
  TError,
  { handle: string; data?: CreateProjectInvitationRequest },
  TContext
> => {
  const mutationKey = ['createProjectInvitation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProjectInvitation>>,
    { handle: string; data?: CreateProjectInvitationRequest }
  > = (props) => {
    const { handle, data } = props ?? {};

    return createProjectInvitation(handle, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProjectInvitation>>
>;
export type CreateProjectInvitationMutationBody =
  | CreateProjectInvitationRequest
  | undefined;
export type CreateProjectInvitationMutationError = ErrorType<unknown>;

/**
 * @summary Create Project Invitation
 */
export const useCreateProjectInvitation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProjectInvitation>>,
      TError,
      { handle: string; data?: CreateProjectInvitationRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProjectInvitation>>,
  TError,
  { handle: string; data?: CreateProjectInvitationRequest },
  TContext
> => {
  return useMutation(
    getCreateProjectInvitationMutationOptions(options),
    queryClient,
  );
};
export type getProjectTeammatesResponse200 = {
  data: GetProjectTeammatesResponse;
  status: 200;
};

export type getProjectTeammatesResponseSuccess =
  getProjectTeammatesResponse200 & {
    headers: Headers;
  };
export type getProjectTeammatesResponse = getProjectTeammatesResponseSuccess;

export const getGetProjectTeammatesUrl = (handle: string) => {
  return `/projects/${handle}/teammates`;
};

/**
 * 프로젝트의 팀원 목록을 조회합니다.
 * @summary Get Project Teammates
 */
export const getProjectTeammates = async (
  handle: string,
  options?: RequestInit,
): Promise<getProjectTeammatesResponse> => {
  return api<getProjectTeammatesResponse>(getGetProjectTeammatesUrl(handle), {
    ...options,
    method: 'GET',
  });
};

export const getGetProjectTeammatesQueryKey = (handle: string) => {
  return [`/projects/${handle}/teammates`] as const;
};

export const getGetProjectTeammatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectTeammates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectTeammates>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectTeammatesQueryKey(handle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectTeammates>>
  > = ({ signal }) =>
    getProjectTeammates(handle, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectTeammates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectTeammatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectTeammates>>
>;
export type GetProjectTeammatesQueryError = ErrorType<unknown>;

export function useGetProjectTeammates<
  TData = Awaited<ReturnType<typeof getProjectTeammates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectTeammates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectTeammates>>,
          TError,
          Awaited<ReturnType<typeof getProjectTeammates>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectTeammates<
  TData = Awaited<ReturnType<typeof getProjectTeammates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectTeammates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectTeammates>>,
          TError,
          Awaited<ReturnType<typeof getProjectTeammates>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectTeammates<
  TData = Awaited<ReturnType<typeof getProjectTeammates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectTeammates>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Teammates
 */

export function useGetProjectTeammates<
  TData = Awaited<ReturnType<typeof getProjectTeammates>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectTeammates>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectTeammatesQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type addTeammateResponse201 = {
  data: void;
  status: 201;
};

export type addTeammateResponseSuccess = addTeammateResponse201 & {
  headers: Headers;
};
export type addTeammateResponse = addTeammateResponseSuccess;

export const getAddTeammateUrl = (handle: string) => {
  return `/projects/${handle}/teammates`;
};

/**
 * 프로젝트에 팀원을 추가합니다.
 * @summary Add Teammate
 */
export const addTeammate = async (
  handle: string,
  addTeammateRequest?: AddTeammateRequest,
  options?: RequestInit,
): Promise<addTeammateResponse> => {
  return api<addTeammateResponse>(getAddTeammateUrl(handle), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addTeammateRequest),
  });
};

export const getAddTeammateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addTeammate>>,
    TError,
    { handle: string; data?: AddTeammateRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addTeammate>>,
  TError,
  { handle: string; data?: AddTeammateRequest },
  TContext
> => {
  const mutationKey = ['addTeammate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addTeammate>>,
    { handle: string; data?: AddTeammateRequest }
  > = (props) => {
    const { handle, data } = props ?? {};

    return addTeammate(handle, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddTeammateMutationResult = NonNullable<
  Awaited<ReturnType<typeof addTeammate>>
>;
export type AddTeammateMutationBody = AddTeammateRequest | undefined;
export type AddTeammateMutationError = ErrorType<unknown>;

/**
 * @summary Add Teammate
 */
export const useAddTeammate = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addTeammate>>,
      TError,
      { handle: string; data?: AddTeammateRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addTeammate>>,
  TError,
  { handle: string; data?: AddTeammateRequest },
  TContext
> => {
  return useMutation(getAddTeammateMutationOptions(options), queryClient);
};
export type unfollowProjectResponse204 = {
  data: void;
  status: 204;
};

export type unfollowProjectResponseSuccess = unfollowProjectResponse204 & {
  headers: Headers;
};
export type unfollowProjectResponse = unfollowProjectResponseSuccess;

export const getUnfollowProjectUrl = (handle: string) => {
  return `/projects/${handle}/unfollow`;
};

/**
 * 프로젝트 팔로우를 취소합니다.
 * @summary Unfollow Project
 */
export const unfollowProject = async (
  handle: string,
  options?: RequestInit,
): Promise<unfollowProjectResponse> => {
  return api<unfollowProjectResponse>(getUnfollowProjectUrl(handle), {
    ...options,
    method: 'DELETE',
  });
};

export const getUnfollowProjectMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unfollowProject>>,
    TError,
    { handle: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unfollowProject>>,
  TError,
  { handle: string },
  TContext
> => {
  const mutationKey = ['unfollowProject'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unfollowProject>>,
    { handle: string }
  > = (props) => {
    const { handle } = props ?? {};

    return unfollowProject(handle, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnfollowProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof unfollowProject>>
>;

export type UnfollowProjectMutationError = ErrorType<unknown>;

/**
 * @summary Unfollow Project
 */
export const useUnfollowProject = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unfollowProject>>,
      TError,
      { handle: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof unfollowProject>>,
  TError,
  { handle: string },
  TContext
> => {
  return useMutation(getUnfollowProjectMutationOptions(options), queryClient);
};
export type cancelProjectInvitationResponse204 = {
  data: void;
  status: 204;
};

export type cancelProjectInvitationResponseSuccess =
  cancelProjectInvitationResponse204 & {
    headers: Headers;
  };
export type cancelProjectInvitationResponse =
  cancelProjectInvitationResponseSuccess;

export const getCancelProjectInvitationUrl = (
  handle: string,
  invitationId: string,
) => {
  return `/projects/${handle}/invitations/${invitationId}`;
};

/**
 * 프로젝트 초대를 취소합니다.
 * @summary Cancel Project Invitation
 */
export const cancelProjectInvitation = async (
  handle: string,
  invitationId: string,
  options?: RequestInit,
): Promise<cancelProjectInvitationResponse> => {
  return api<cancelProjectInvitationResponse>(
    getCancelProjectInvitationUrl(handle, invitationId),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getCancelProjectInvitationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelProjectInvitation>>,
    TError,
    { handle: string; invitationId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelProjectInvitation>>,
  TError,
  { handle: string; invitationId: string },
  TContext
> => {
  const mutationKey = ['cancelProjectInvitation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelProjectInvitation>>,
    { handle: string; invitationId: string }
  > = (props) => {
    const { handle, invitationId } = props ?? {};

    return cancelProjectInvitation(handle, invitationId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelProjectInvitationMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelProjectInvitation>>
>;

export type CancelProjectInvitationMutationError = ErrorType<unknown>;

/**
 * @summary Cancel Project Invitation
 */
export const useCancelProjectInvitation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelProjectInvitation>>,
      TError,
      { handle: string; invitationId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelProjectInvitation>>,
  TError,
  { handle: string; invitationId: string },
  TContext
> => {
  return useMutation(
    getCancelProjectInvitationMutationOptions(options),
    queryClient,
  );
};
export type removeTeammateResponse204 = {
  data: void;
  status: 204;
};

export type removeTeammateResponseSuccess = removeTeammateResponse204 & {
  headers: Headers;
};
export type removeTeammateResponse = removeTeammateResponseSuccess;

export const getRemoveTeammateUrl = (
  handle: string,
  teammateHandle: string,
) => {
  return `/projects/${handle}/teammates/${teammateHandle}`;
};

/**
 * 프로젝트에서 팀원을 제거합니다.
 * @summary Remove Teammate
 */
export const removeTeammate = async (
  handle: string,
  teammateHandle: string,
  options?: RequestInit,
): Promise<removeTeammateResponse> => {
  return api<removeTeammateResponse>(
    getRemoveTeammateUrl(handle, teammateHandle),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getRemoveTeammateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeTeammate>>,
    TError,
    { handle: string; teammateHandle: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeTeammate>>,
  TError,
  { handle: string; teammateHandle: string },
  TContext
> => {
  const mutationKey = ['removeTeammate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeTeammate>>,
    { handle: string; teammateHandle: string }
  > = (props) => {
    const { handle, teammateHandle } = props ?? {};

    return removeTeammate(handle, teammateHandle, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveTeammateMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeTeammate>>
>;

export type RemoveTeammateMutationError = ErrorType<unknown>;

/**
 * @summary Remove Teammate
 */
export const useRemoveTeammate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeTeammate>>,
      TError,
      { handle: string; teammateHandle: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeTeammate>>,
  TError,
  { handle: string; teammateHandle: string },
  TContext
> => {
  return useMutation(getRemoveTeammateMutationOptions(options), queryClient);
};
export type updateTeammateResponse204 = {
  data: void;
  status: 204;
};

export type updateTeammateResponseSuccess = updateTeammateResponse204 & {
  headers: Headers;
};
export type updateTeammateResponse = updateTeammateResponseSuccess;

export const getUpdateTeammateUrl = (
  handle: string,
  teammateHandle: string,
) => {
  return `/projects/${handle}/teammates/${teammateHandle}`;
};

/**
 * 프로젝트 팀원의 역할을 수정합니다.
 * @summary Update Teammate
 */
export const updateTeammate = async (
  handle: string,
  teammateHandle: string,
  updateTeammateRequest?: UpdateTeammateRequest,
  options?: RequestInit,
): Promise<updateTeammateResponse> => {
  return api<updateTeammateResponse>(
    getUpdateTeammateUrl(handle, teammateHandle),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(updateTeammateRequest),
    },
  );
};

export const getUpdateTeammateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTeammate>>,
    TError,
    { handle: string; teammateHandle: string; data?: UpdateTeammateRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTeammate>>,
  TError,
  { handle: string; teammateHandle: string; data?: UpdateTeammateRequest },
  TContext
> => {
  const mutationKey = ['updateTeammate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTeammate>>,
    { handle: string; teammateHandle: string; data?: UpdateTeammateRequest }
  > = (props) => {
    const { handle, teammateHandle, data } = props ?? {};

    return updateTeammate(handle, teammateHandle, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTeammateMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTeammate>>
>;
export type UpdateTeammateMutationBody = UpdateTeammateRequest | undefined;
export type UpdateTeammateMutationError = ErrorType<unknown>;

/**
 * @summary Update Teammate
 */
export const useUpdateTeammate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTeammate>>,
      TError,
      { handle: string; teammateHandle: string; data?: UpdateTeammateRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateTeammate>>,
  TError,
  { handle: string; teammateHandle: string; data?: UpdateTeammateRequest },
  TContext
> => {
  return useMutation(getUpdateTeammateMutationOptions(options), queryClient);
};
export type searchProjectsResponse200 = {
  data: GetProjectsResponse;
  status: 200;
};

export type searchProjectsResponseSuccess = searchProjectsResponse200 & {
  headers: Headers;
};
export type searchProjectsResponse = searchProjectsResponseSuccess;

export const getSearchProjectsUrl = (params: SearchProjectsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/search/projects?${stringifiedParams}`
    : `/search/projects`;
};

/**
 * 검색어로 프로젝트를 검색합니다.
 * @summary Search Projects
 */
export const searchProjects = async (
  params: SearchProjectsParams,
  options?: RequestInit,
): Promise<searchProjectsResponse> => {
  return api<searchProjectsResponse>(getSearchProjectsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchProjectsQueryKey = (params?: SearchProjectsParams) => {
  return [`/search/projects`, ...(params ? [params] : [])] as const;
};

export const getSearchProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchProjects>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchProjectsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchProjects>>> = ({
    signal,
  }) => searchProjects(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchProjects>>
>;
export type SearchProjectsQueryError = ErrorType<unknown>;

export function useSearchProjects<
  TData = Awaited<ReturnType<typeof searchProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchProjectsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchProjects>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProjects>>,
          TError,
          Awaited<ReturnType<typeof searchProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchProjects<
  TData = Awaited<ReturnType<typeof searchProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchProjects>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchProjects>>,
          TError,
          Awaited<ReturnType<typeof searchProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchProjects<
  TData = Awaited<ReturnType<typeof searchProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchProjects>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Projects
 */

export function useSearchProjects<
  TData = Awaited<ReturnType<typeof searchProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchProjects>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchProjectsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type searchMyProjectsResponse200 = {
  data: GetProjectsResponse;
  status: 200;
};

export type searchMyProjectsResponseSuccess = searchMyProjectsResponse200 & {
  headers: Headers;
};
export type searchMyProjectsResponse = searchMyProjectsResponseSuccess;

export const getSearchMyProjectsUrl = (params: SearchMyProjectsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/search/projects/my?${stringifiedParams}`
    : `/search/projects/my`;
};

/**
 * 내 프로젝트를 검색어로 검색합니다.
 * @summary Search My Projects
 */
export const searchMyProjects = async (
  params: SearchMyProjectsParams,
  options?: RequestInit,
): Promise<searchMyProjectsResponse> => {
  return api<searchMyProjectsResponse>(getSearchMyProjectsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchMyProjectsQueryKey = (
  params?: SearchMyProjectsParams,
) => {
  return [`/search/projects/my`, ...(params ? [params] : [])] as const;
};

export const getSearchMyProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchMyProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchMyProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchMyProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSearchMyProjectsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof searchMyProjects>>
  > = ({ signal }) => searchMyProjects(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchMyProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchMyProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchMyProjects>>
>;
export type SearchMyProjectsQueryError = ErrorType<unknown>;

export function useSearchMyProjects<
  TData = Awaited<ReturnType<typeof searchMyProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchMyProjectsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchMyProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchMyProjects>>,
          TError,
          Awaited<ReturnType<typeof searchMyProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchMyProjects<
  TData = Awaited<ReturnType<typeof searchMyProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchMyProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchMyProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchMyProjects>>,
          TError,
          Awaited<ReturnType<typeof searchMyProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchMyProjects<
  TData = Awaited<ReturnType<typeof searchMyProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchMyProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchMyProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search My Projects
 */

export function useSearchMyProjects<
  TData = Awaited<ReturnType<typeof searchMyProjects>>,
  TError = ErrorType<unknown>,
>(
  params: SearchMyProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof searchMyProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchMyProjectsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getFollowedProjectsResponse200 = {
  data: GetProjectsResponse;
  status: 200;
};

export type getFollowedProjectsResponseSuccess =
  getFollowedProjectsResponse200 & {
    headers: Headers;
  };
export type getFollowedProjectsResponse = getFollowedProjectsResponseSuccess;

export const getGetFollowedProjectsUrl = (handle: string) => {
  return `/users/${handle}/followed-projects`;
};

/**
 * 유저가 팔로우하는 프로젝트 목록을 조회합니다.
 * @summary Get Followed Projects
 */
export const getFollowedProjects = async (
  handle: string,
  options?: RequestInit,
): Promise<getFollowedProjectsResponse> => {
  return api<getFollowedProjectsResponse>(getGetFollowedProjectsUrl(handle), {
    ...options,
    method: 'GET',
  });
};

export const getGetFollowedProjectsQueryKey = (handle: string) => {
  return [`/users/${handle}/followed-projects`] as const;
};

export const getGetFollowedProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFollowedProjects>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFollowedProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFollowedProjectsQueryKey(handle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFollowedProjects>>
  > = ({ signal }) =>
    getFollowedProjects(handle, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFollowedProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFollowedProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFollowedProjects>>
>;
export type GetFollowedProjectsQueryError = ErrorType<unknown>;

export function useGetFollowedProjects<
  TData = Awaited<ReturnType<typeof getFollowedProjects>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFollowedProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowedProjects>>,
          TError,
          Awaited<ReturnType<typeof getFollowedProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowedProjects<
  TData = Awaited<ReturnType<typeof getFollowedProjects>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFollowedProjects>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowedProjects>>,
          TError,
          Awaited<ReturnType<typeof getFollowedProjects>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowedProjects<
  TData = Awaited<ReturnType<typeof getFollowedProjects>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFollowedProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Followed Projects
 */

export function useGetFollowedProjects<
  TData = Awaited<ReturnType<typeof getFollowedProjects>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFollowedProjects>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFollowedProjectsQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProjectsByUserResponse200 = {
  data: GetProjectsResponse;
  status: 200;
};

export type getProjectsByUserResponseSuccess = getProjectsByUserResponse200 & {
  headers: Headers;
};
export type getProjectsByUserResponse = getProjectsByUserResponseSuccess;

export const getGetProjectsByUserUrl = (handle: string) => {
  return `/users/${handle}/projects`;
};

/**
 * 유저 핸들로 해당 유저의 프로젝트 목록을 조회합니다.
 * @summary Get Projects By User
 */
export const getProjectsByUser = async (
  handle: string,
  options?: RequestInit,
): Promise<getProjectsByUserResponse> => {
  return api<getProjectsByUserResponse>(getGetProjectsByUserUrl(handle), {
    ...options,
    method: 'GET',
  });
};

export const getGetProjectsByUserQueryKey = (handle: string) => {
  return [`/users/${handle}/projects`] as const;
};

export const getGetProjectsByUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectsByUser>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectsByUserQueryKey(handle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectsByUser>>
  > = ({ signal }) => getProjectsByUser(handle, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectsByUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectsByUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectsByUser>>
>;
export type GetProjectsByUserQueryError = ErrorType<unknown>;

export function useGetProjectsByUser<
  TData = Awaited<ReturnType<typeof getProjectsByUser>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByUser>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsByUser>>,
          TError,
          Awaited<ReturnType<typeof getProjectsByUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectsByUser<
  TData = Awaited<ReturnType<typeof getProjectsByUser>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByUser>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsByUser>>,
          TError,
          Awaited<ReturnType<typeof getProjectsByUser>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectsByUser<
  TData = Awaited<ReturnType<typeof getProjectsByUser>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Projects By User
 */

export function useGetProjectsByUser<
  TData = Awaited<ReturnType<typeof getProjectsByUser>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByUser>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectsByUserQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
