apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: sync
data:
  AI_PROVIDER: "ollama"
  OLLAMA_URL: "http://host.minikube.internal:11435"
  OLLAMA_MODEL: "gemma3:270m"
  OLLAMA_EMBEDDING_MODEL: "nomic-embed-text"

  APP_CORS_ALLOWED_ORIGINS: "http://localhost:3000"
  APP_OAUTH2_FRONTEND_REDIRECT_URI: "http://localhost:3000"

  SPRING_CLOUD_AWS_ENDPOINT: "http://host.minikube.internal:4566"
  SPRING_CLOUD_AWS_REGION_STATIC: "us-east-1"
  SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY: "skkil"
  SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY: "sync"
  SPRING_CLOUD_AWS_S3_PATH_STYLE_ACCESS_ENABLED: "true"
