apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: server-secret
  namespace: sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: server-secret
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
      remoteRef:
        key: sync/local/server/app
        property: OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
    - secretKey: OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: sync/local/server/app
        property: OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: sync/local/server/app
        property: MAIL_USERNAME
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: sync/local/server/app
        property: MAIL_PASSWORD
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: sync/local/server/app
        property: SLACK_WEBHOOK_URL
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: sync/local/postgres/password
        property: jdbc_url
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: sync/local/postgres/password
        property: username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: sync/local/postgres/password
        property: password
