openapi: 3.0.1
info:
  title: sync
  description: ""
  version: 0.0.1
servers:
- url: ""
tags: []
paths:
  /experiences/project/{experienceId}/reflections:
    get:
      tags:
      - reflection
      summary: Get Reflections
      description: Get Reflections
      operationId: GetProjectExperienceReflections
      parameters:
      - name: experienceId
        in: path
        description: Project Experience ID
        required: true
        schema:
          type: string
      - name: cursor
        in: query
        description: Cursor for pagination (optional)
        required: true
        schema:
          type: string
      - name: size
        in: query
        description: "Number of items per page (required, minimum 1)"
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetReflectionsResponse"
              examples:
                GetProjectExperienceReflections:
                  value: "{\"reflections\":{\"content\":[{\"id\":1,\"author\":{\"\
                    id\":1,\"name\":\"User\"},\"project\":{\"id\":1,\"name\":\"Project\"\
                    },\"content\":\"Reflection Content\",\"createdAt\":\"1970-01-01T00:00:00\"\
                    }],\"hasNext\":true,\"nextCursor\":null}}"
  /media:
    post:
      tags:
      - media
      summary: Upload Media
      description: Upload Media
      operationId: UploadMedia
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadMediaRequest"
            examples:
              UploadMedia:
                value: "{\"mediaType\":\"image/jpeg\",\"mediaContext\":\"profile-image\"\
                  ,\"fileName\":\"test.jpg\",\"fileSize\":100}"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadMediaResponse"
              examples:
                UploadMedia:
                  value: |-
                    {
                      "mediaId" : 1,
                      "uploadUrl" : "https://example.com/upload",
                      "expiresAt" : "1970-01-01T00:00:00"
                    }
  /profiles/me:
    get:
      tags:
      - profile
      summary: Get Authenticated User Profile
      description: Get Authenticated User Profile
      operationId: GetAuthenticatedUser
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetProfileResponse"
              examples:
                GetAuthenticatedUser:
                  value: "{\"userId\":\"1\",\"handle\":\"username\",\"name\":\"name\"\
                    ,\"email\":\"email@example.com\",\"bio\":\"bio\",\"profession\"\
                    :\"profession\",\"profileImageUrl\":\"https://example.com/profile-image.png\"\
                    ,\"isFollowing\":true,\"isOnboarded\":true,\"isAuthenticatedUser\"\
                    :false,\"role\":\"USER\",\"contacts\":null}"
    patch:
      tags:
      - profile
      summary: Update Profile
      description: Update Profile
      operationId: UpdateProfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProfileRequest"
            examples:
              UpdateProfile:
                value: "{\"name\":\"name\",\"handle\":\"username\",\"profileImageId\"\
                  :1,\"removeProfileImage\":false,\"isOnboarded\":true,\"bio\":\"\
                  bio\",\"profession\":\"profession\",\"contacts\":{\"custom\":\"\
                  https://example.com\",\"linkedin\":\"linkedinUser\",\"github\":\"\
                  githubUser\",\"instagram\":\"instagramUser\",\"twitter\":\"twitterUser\"\
                  }}"
      responses:
        "204":
          description: "204"
  /profiles/{handle}:
    get:
      tags:
      - profile
      summary: Get Profile By Handle
      description: Get Profile By Handle
      operationId: GetProfileByHandle
      parameters:
      - name: handle
        in: path
        description: Handle
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetProfileResponse"
              examples:
                GetProfileByHandle:
                  value: "{\"userId\":\"1\",\"handle\":\"username\",\"name\":\"name\"\
                    ,\"email\":\"email@example.com\",\"bio\":\"bio\",\"profession\"\
                    :\"profession\",\"profileImageUrl\":\"https://example.com/profile-image.png\"\
                    ,\"isFollowing\":true,\"isOnboarded\":true,\"isAuthenticatedUser\"\
                    :false,\"role\":\"USER\",\"contacts\":null}"
  /reflections:
    get:
      tags:
      - reflection
      summary: Get Reflections
      description: Get Reflections
      operationId: GetReflections
      parameters:
      - name: cursor
        in: query
        description: Cursor for pagination (optional)
        required: true
        schema:
          type: string
      - name: size
        in: query
        description: "Number of items per page (required, minimum 1)"
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetReflectionsResponse"
              examples:
                GetReflections:
                  value: "{\"reflections\":{\"content\":[{\"id\":1,\"author\":{\"\
                    id\":1,\"name\":\"User\"},\"project\":{\"id\":1,\"name\":\"Project\"\
                    },\"content\":\"Reflection Content\",\"createdAt\":\"1970-01-01T00:00:00\"\
                    }],\"hasNext\":true,\"nextCursor\":null}}"
    post:
      tags:
      - reflection
      summary: Create Reflection
      description: Create Reflection
      operationId: CreateReflection
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReflectionRequest"
            examples:
              CreateReflection:
                value: "{\"experienceId\":1,\"content\":\"This is a reflection content.\"\
                  }"
      responses:
        "201":
          description: "201"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateReflectionResponse"
              examples:
                CreateReflection:
                  value: |-
                    {
                      "id" : 1
                    }
  /reflections/{reflectionId}:
    delete:
      tags:
      - reflection
      summary: Delete Reflection
      description: Delete Reflection
      operationId: DeleteReflection
      parameters:
      - name: reflectionId
        in: path
        description: Reflection ID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: "204"
    patch:
      tags:
      - reflection
      summary: Update Reflection
      description: Update Reflection
      operationId: UpdateReflection
      parameters:
      - name: reflectionId
        in: path
        description: Reflection ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateReflectionRequest"
            examples:
              UpdateReflection:
                value: "{\"experienceId\":1,\"content\":\"This is a reflection content.\"\
                  }"
      responses:
        "204":
          description: "204"
  /users/{userId}/reflections:
    get:
      tags:
      - reflection
      summary: Get Reflections
      description: Get Reflections
      operationId: GetUserReflections
      parameters:
      - name: userId
        in: path
        description: User ID
        required: true
        schema:
          type: string
      - name: cursor
        in: query
        description: Cursor for pagination (optional)
        required: true
        schema:
          type: string
      - name: size
        in: query
        description: "Number of items per page (required, minimum 1)"
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetReflectionsResponse"
              examples:
                GetUserReflections:
                  value: "{\"reflections\":{\"content\":[{\"id\":1,\"author\":{\"\
                    id\":1,\"name\":\"User\"},\"project\":{\"id\":1,\"name\":\"Project\"\
                    },\"content\":\"Reflection Content\",\"createdAt\":\"1970-01-01T00:00:00\"\
                    }],\"hasNext\":true,\"nextCursor\":null}}"
components:
  schemas:
    UploadMediaResponse:
      title: UploadMediaResponse
      required:
      - expiresAt
      - mediaId
      - uploadUrl
      type: object
      properties:
        uploadUrl:
          type: string
          description: Pre-signed Upload URL
        mediaId:
          type: number
          description: Media ID
        expiresAt:
          type: string
          description: Expiration Time
    CreateReflectionRequest:
      title: CreateReflectionRequest
      required:
      - content
      type: object
      properties:
        experienceId:
          type: number
          description: Experience ID
          nullable: true
        content:
          type: string
          description: Content
    GetReflectionsResponse:
      title: GetReflectionsResponse
      type: object
      properties:
        reflections:
          required:
          - content
          - hasNext
          type: object
          properties:
            nextCursor:
              type: string
              description: Next Cursor
              nullable: true
            hasNext:
              type: boolean
              description: Has Next
            content:
              type: array
              description: Content
              items:
                required:
                - content
                - createdAt
                - id
                type: object
                properties:
                  createdAt:
                    type: string
                    description: Creation Timestamp
                  author:
                    required:
                    - id
                    - name
                    type: object
                    properties:
                      name:
                        type: string
                        description: Author Name
                      id:
                        type: number
                        description: Author User ID
                  project:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Project Name
                        nullable: true
                      id:
                        type: number
                        description: Project ID
                        nullable: true
                  id:
                    type: number
                    description: Reflection ID
                  content:
                    type: string
                    description: Reflection Content
    UpdateReflectionRequest:
      title: UpdateReflectionRequest
      required:
      - content
      type: object
      properties:
        experienceId:
          type: number
          description: Experience ID
          nullable: true
        content:
          type: string
          description: Content
    GetProfileResponse:
      title: GetProfileResponse
      required:
      - bio
      - email
      - isAuthenticatedUser
      - isFollowing
      - isOnboarded
      - name
      - profession
      - profileImageUrl
      - role
      - userId
      type: object
      properties:
        profession:
          type: string
          description: Profession
        isAuthenticatedUser:
          type: boolean
          description: Is Authenticated User
        role:
          type: string
          description: Role
        isFollowing:
          type: boolean
          description: Is Following
        name:
          type: string
          description: Full Name
        bio:
          type: string
          description: Bio
        handle:
          type: string
          description: Handle
          nullable: true
        profileImageUrl:
          type: string
          description: Profile Image URL
        userId:
          type: string
          description: ID
        contacts:
          type: object
          properties:
            twitter:
              type: string
              description: Twitter Username
              nullable: true
            github:
              type: string
              description: GitHub Username
              nullable: true
            custom:
              type: string
              description: Custom Contact
              nullable: true
            instagram:
              type: string
              description: Instagram Username
              nullable: true
            linkedin:
              type: string
              description: LinkedIn Username
              nullable: true
          description: Contacts
        email:
          type: string
          description: E-mail
        isOnboarded:
          type: boolean
          description: Is Onboarded
    UpdateProfileRequest:
      title: UpdateProfileRequest
      type: object
      properties:
        profession:
          type: string
          description: Profession
          nullable: true
        profileImageId:
          type: number
          description: Profile Image ID
          nullable: true
        name:
          type: string
          description: Full Name
          nullable: true
        bio:
          type: string
          description: Bio
          nullable: true
        handle:
          type: string
          description: Handle
          nullable: true
        removeProfileImage:
          type: boolean
          description: Remove Profile Image
          nullable: true
        contacts:
          type: object
          properties:
            twitter:
              type: string
              description: Twitter Username
              nullable: true
            github:
              type: string
              description: GitHub Username
              nullable: true
            custom:
              type: string
              description: Custom Contact
              nullable: true
            instagram:
              type: string
              description: Instagram Username
              nullable: true
            linkedin:
              type: string
              description: LinkedIn Username
              nullable: true
          description: Contacts
        isOnboarded:
          type: boolean
          description: Is Onboarded
          nullable: true
    UploadMediaRequest:
      title: UploadMediaRequest
      required:
      - fileName
      - fileSize
      - mediaContext
      - mediaType
      type: object
      properties:
        fileName:
          type: string
          description: File Name
        fileSize:
          type: number
          description: File Size
        mediaContext:
          type: string
          description: Media Context
        mediaType:
          type: string
          description: Media Type
    CreateReflectionResponse:
      title: CreateReflectionResponse
      required:
      - id
      type: object
      properties:
        id:
          type: number
          description: Reflection ID
