/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreatePostRequest,
  CreatePostResponse,
  GetPostActivitiesParams,
  GetPostActivitiesResponse,
  GetPostResponse,
  GetPostsByProjectParams,
  GetPostsParams,
  GetPostsResponse,
  GetUserPostsParams,
  SearchPostsParams,
  SearchPostsResponse,
  UpdatePostRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get Posts
 * @summary Get Posts
 */
export type getPostsResponse200 = {
  data: GetPostsResponse;
  status: 200;
};

export type getPostsResponseSuccess = getPostsResponse200 & {
  headers: Headers;
};
export type getPostsResponse = getPostsResponseSuccess;

export const getGetPostsUrl = (params?: GetPostsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/posts?${stringifiedParams}`
    : `/posts`;
};

export const getPosts = async (
  params?: GetPostsParams,
  options?: RequestInit,
): Promise<getPostsResponse> => {
  return api<getPostsResponse>(getGetPostsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetPostsInfiniteQueryKey = (params?: GetPostsParams) => {
  return ['infinite', `/posts`, ...(params ? [params] : [])] as const;
};

export const getGetPostsQueryKey = (params?: GetPostsParams) => {
  return [`/posts`, ...(params ? [params] : [])] as const;
};

export const getGetPostsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPosts>>,
    GetPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData,
        QueryKey,
        GetPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPostsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPosts>>,
    QueryKey,
    GetPostsParams['after']
  > = ({ signal, pageParam }) =>
    getPosts(
      { ...params, after: pageParam || params?.['after'] },
      { signal, ...requestOptions },
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData,
    QueryKey,
    GetPostsParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPosts>>
>;
export type GetPostsInfiniteQueryError = ErrorType<unknown>;

export function useGetPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPosts>>,
    GetPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPostsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData,
        QueryKey,
        GetPostsParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPosts>>,
    GetPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData,
        QueryKey,
        GetPostsParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPosts>>,
    GetPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData,
        QueryKey,
        GetPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Posts
 */

export function useGetPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPosts>>,
    GetPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPosts>>,
        TError,
        TData,
        QueryKey,
        GetPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({
    signal,
  }) => getPosts(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPosts>>
>;
export type GetPostsQueryError = ErrorType<unknown>;

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Posts
 */

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create Post
 * @summary Create Post
 */
export type createPostResponse201 = {
  data: CreatePostResponse;
  status: 201;
};

export type createPostResponseSuccess = createPostResponse201 & {
  headers: Headers;
};
export type createPostResponse = createPostResponseSuccess;

export const getCreatePostUrl = () => {
  return `/posts`;
};

export const createPost = async (
  createPostRequest: CreatePostRequest,
  options?: RequestInit,
): Promise<createPostResponse> => {
  return api<createPostResponse>(getCreatePostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPostRequest),
  });
};

export const getCreatePostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPost>>,
    TError,
    { data: CreatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPost>>,
  TError,
  { data: CreatePostRequest },
  TContext
> => {
  const mutationKey = ['createPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPost>>,
    { data: CreatePostRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPost>>
>;
export type CreatePostMutationBody = CreatePostRequest;
export type CreatePostMutationError = ErrorType<unknown>;

/**
 * @summary Create Post
 */
export const useCreatePost = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPost>>,
      TError,
      { data: CreatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPost>>,
  TError,
  { data: CreatePostRequest },
  TContext
> => {
  return useMutation(getCreatePostMutationOptions(options), queryClient);
};
/**
 * Delete Post
 * @summary Delete Post
 */
export type deletePostResponse204 = {
  data: void;
  status: 204;
};

export type deletePostResponseSuccess = deletePostResponse204 & {
  headers: Headers;
};
export type deletePostResponse = deletePostResponseSuccess;

export const getDeletePostUrl = (postId: string) => {
  return `/posts/${postId}`;
};

export const deletePost = async (
  postId: string,
  options?: RequestInit,
): Promise<deletePostResponse> => {
  return api<deletePostResponse>(getDeletePostUrl(postId), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeletePostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePost>>,
    TError,
    { postId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePost>>,
  TError,
  { postId: string },
  TContext
> => {
  const mutationKey = ['deletePost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePost>>,
    { postId: string }
  > = (props) => {
    const { postId } = props ?? {};

    return deletePost(postId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePost>>
>;

export type DeletePostMutationError = ErrorType<unknown>;

/**
 * @summary Delete Post
 */
export const useDeletePost = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePost>>,
      TError,
      { postId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePost>>,
  TError,
  { postId: string },
  TContext
> => {
  return useMutation(getDeletePostMutationOptions(options), queryClient);
};
/**
 * Update Post
 * @summary Update Post
 */
export type updatePostResponse204 = {
  data: void;
  status: 204;
};

export type updatePostResponseSuccess = updatePostResponse204 & {
  headers: Headers;
};
export type updatePostResponse = updatePostResponseSuccess;

export const getUpdatePostUrl = (postId: string) => {
  return `/posts/${postId}`;
};

export const updatePost = async (
  postId: string,
  updatePostRequest: UpdatePostRequest,
  options?: RequestInit,
): Promise<updatePostResponse> => {
  return api<updatePostResponse>(getUpdatePostUrl(postId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePostRequest),
  });
};

export const getUpdatePostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePost>>,
    TError,
    { postId: string; data: UpdatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePost>>,
  TError,
  { postId: string; data: UpdatePostRequest },
  TContext
> => {
  const mutationKey = ['updatePost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePost>>,
    { postId: string; data: UpdatePostRequest }
  > = (props) => {
    const { postId, data } = props ?? {};

    return updatePost(postId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePostMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePost>>
>;
export type UpdatePostMutationBody = UpdatePostRequest;
export type UpdatePostMutationError = ErrorType<unknown>;

/**
 * @summary Update Post
 */
export const useUpdatePost = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePost>>,
      TError,
      { postId: string; data: UpdatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePost>>,
  TError,
  { postId: string; data: UpdatePostRequest },
  TContext
> => {
  return useMutation(getUpdatePostMutationOptions(options), queryClient);
};
/**
 * Get Post By Slug
 * @summary Get Post By Slug
 */
export type getPostBySlugResponse200 = {
  data: GetPostResponse;
  status: 200;
};

export type getPostBySlugResponseSuccess = getPostBySlugResponse200 & {
  headers: Headers;
};
export type getPostBySlugResponse = getPostBySlugResponseSuccess;

export const getGetPostBySlugUrl = (slug: string) => {
  return `/posts/${slug}`;
};

export const getPostBySlug = async (
  slug: string,
  options?: RequestInit,
): Promise<getPostBySlugResponse> => {
  return api<getPostBySlugResponse>(getGetPostBySlugUrl(slug), {
    ...options,
    method: 'GET',
  });
};

export const getGetPostBySlugQueryKey = (slug: string) => {
  return [`/posts/${slug}`] as const;
};

export const getGetPostBySlugQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostBySlugQueryKey(slug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostBySlug>>> = ({
    signal,
  }) => getPostBySlug(slug, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostBySlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostBySlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostBySlug>>
>;
export type GetPostBySlugQueryError = ErrorType<unknown>;

export function useGetPostBySlug<
  TData = Awaited<ReturnType<typeof getPostBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostBySlug>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostBySlug>>,
          TError,
          Awaited<ReturnType<typeof getPostBySlug>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostBySlug<
  TData = Awaited<ReturnType<typeof getPostBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostBySlug>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostBySlug>>,
          TError,
          Awaited<ReturnType<typeof getPostBySlug>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostBySlug<
  TData = Awaited<ReturnType<typeof getPostBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Post By Slug
 */

export function useGetPostBySlug<
  TData = Awaited<ReturnType<typeof getPostBySlug>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPostBySlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostBySlugQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get Post Activities
 * @summary Get Post Activities
 */
export type getPostActivitiesResponse200 = {
  data: GetPostActivitiesResponse;
  status: 200;
};

export type getPostActivitiesResponseSuccess = getPostActivitiesResponse200 & {
  headers: Headers;
};
export type getPostActivitiesResponse = getPostActivitiesResponseSuccess;

export const getGetPostActivitiesUrl = (
  handle: string,
  params: GetPostActivitiesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/profiles/${handle}/posts/activities?${stringifiedParams}`
    : `/profiles/${handle}/posts/activities`;
};

export const getPostActivities = async (
  handle: string,
  params: GetPostActivitiesParams,
  options?: RequestInit,
): Promise<getPostActivitiesResponse> => {
  return api<getPostActivitiesResponse>(
    getGetPostActivitiesUrl(handle, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetPostActivitiesQueryKey = (
  handle: string,
  params?: GetPostActivitiesParams,
) => {
  return [
    `/profiles/${handle}/posts/activities`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetPostActivitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostActivities>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: GetPostActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostActivities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPostActivitiesQueryKey(handle, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPostActivities>>
  > = ({ signal }) =>
    getPostActivities(handle, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!handle,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostActivities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostActivitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostActivities>>
>;
export type GetPostActivitiesQueryError = ErrorType<unknown>;

export function useGetPostActivities<
  TData = Awaited<ReturnType<typeof getPostActivities>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: GetPostActivitiesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostActivities>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostActivities>>,
          TError,
          Awaited<ReturnType<typeof getPostActivities>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostActivities<
  TData = Awaited<ReturnType<typeof getPostActivities>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: GetPostActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostActivities>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostActivities>>,
          TError,
          Awaited<ReturnType<typeof getPostActivities>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostActivities<
  TData = Awaited<ReturnType<typeof getPostActivities>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: GetPostActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostActivities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Post Activities
 */

export function useGetPostActivities<
  TData = Awaited<ReturnType<typeof getPostActivities>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: GetPostActivitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostActivities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostActivitiesQueryOptions(
    handle,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get Posts By Project
 * @summary Get Posts By Project
 */
export type getPostsByProjectResponse200 = {
  data: GetPostsResponse;
  status: 200;
};

export type getPostsByProjectResponseSuccess = getPostsByProjectResponse200 & {
  headers: Headers;
};
export type getPostsByProjectResponse = getPostsByProjectResponseSuccess;

export const getGetPostsByProjectUrl = (
  handle: string,
  params?: GetPostsByProjectParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/projects/${handle}/posts?${stringifiedParams}`
    : `/projects/${handle}/posts`;
};

export const getPostsByProject = async (
  handle: string,
  params?: GetPostsByProjectParams,
  options?: RequestInit,
): Promise<getPostsByProjectResponse> => {
  return api<getPostsByProjectResponse>(
    getGetPostsByProjectUrl(handle, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetPostsByProjectInfiniteQueryKey = (
  handle: string,
  params?: GetPostsByProjectParams,
) => {
  return [
    'infinite',
    `/projects/${handle}/posts`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetPostsByProjectQueryKey = (
  handle: string,
  params?: GetPostsByProjectParams,
) => {
  return [`/projects/${handle}/posts`, ...(params ? [params] : [])] as const;
};

export const getGetPostsByProjectInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostsByProject>>,
    GetPostsByProjectParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData,
        QueryKey,
        GetPostsByProjectParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetPostsByProjectInfiniteQueryKey(handle, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPostsByProject>>,
    QueryKey,
    GetPostsByProjectParams['after']
  > = ({ signal, pageParam }) =>
    getPostsByProject(
      handle,
      { ...params, after: pageParam || params?.['after'] },
      { signal, ...requestOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: !!handle,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getPostsByProject>>,
    TError,
    TData,
    QueryKey,
    GetPostsByProjectParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsByProjectInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostsByProject>>
>;
export type GetPostsByProjectInfiniteQueryError = ErrorType<unknown>;

export function useGetPostsByProjectInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostsByProject>>,
    GetPostsByProjectParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: undefined | GetPostsByProjectParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData,
        QueryKey,
        GetPostsByProjectParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsByProject>>,
          TError,
          Awaited<ReturnType<typeof getPostsByProject>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsByProjectInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostsByProject>>,
    GetPostsByProjectParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData,
        QueryKey,
        GetPostsByProjectParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsByProject>>,
          TError,
          Awaited<ReturnType<typeof getPostsByProject>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsByProjectInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostsByProject>>,
    GetPostsByProjectParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData,
        QueryKey,
        GetPostsByProjectParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Posts By Project
 */

export function useGetPostsByProjectInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getPostsByProject>>,
    GetPostsByProjectParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData,
        QueryKey,
        GetPostsByProjectParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsByProjectInfiniteQueryOptions(
    handle,
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetPostsByProjectQueryOptions = <
  TData = Awaited<ReturnType<typeof getPostsByProject>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPostsByProjectQueryKey(handle, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPostsByProject>>
  > = ({ signal }) =>
    getPostsByProject(handle, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!handle,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPostsByProject>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsByProjectQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPostsByProject>>
>;
export type GetPostsByProjectQueryError = ErrorType<unknown>;

export function useGetPostsByProject<
  TData = Awaited<ReturnType<typeof getPostsByProject>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: undefined | GetPostsByProjectParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsByProject>>,
          TError,
          Awaited<ReturnType<typeof getPostsByProject>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsByProject<
  TData = Awaited<ReturnType<typeof getPostsByProject>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPostsByProject>>,
          TError,
          Awaited<ReturnType<typeof getPostsByProject>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPostsByProject<
  TData = Awaited<ReturnType<typeof getPostsByProject>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Posts By Project
 */

export function useGetPostsByProject<
  TData = Awaited<ReturnType<typeof getPostsByProject>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetPostsByProjectParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPostsByProject>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsByProjectQueryOptions(
    handle,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Search Posts by query string
 * @summary Search Posts
 */
export type searchPostsResponse200 = {
  data: SearchPostsResponse;
  status: 200;
};

export type searchPostsResponseSuccess = searchPostsResponse200 & {
  headers: Headers;
};
export type searchPostsResponse = searchPostsResponseSuccess;

export const getSearchPostsUrl = (params: SearchPostsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/search/posts?${stringifiedParams}`
    : `/search/posts`;
};

export const searchPosts = async (
  params: SearchPostsParams,
  options?: RequestInit,
): Promise<searchPostsResponse> => {
  return api<searchPostsResponse>(getSearchPostsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchPostsQueryKey = (params?: SearchPostsParams) => {
  return [`/search/posts`, ...(params ? [params] : [])] as const;
};

export const getSearchPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof searchPosts>>,
  TError = ErrorType<unknown>,
>(
  params: SearchPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchPostsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPosts>>> = ({
    signal,
  }) => searchPosts(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchPosts>>
>;
export type SearchPostsQueryError = ErrorType<unknown>;

export function useSearchPosts<
  TData = Awaited<ReturnType<typeof searchPosts>>,
  TError = ErrorType<unknown>,
>(
  params: SearchPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPosts>>,
          TError,
          Awaited<ReturnType<typeof searchPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchPosts<
  TData = Awaited<ReturnType<typeof searchPosts>>,
  TError = ErrorType<unknown>,
>(
  params: SearchPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPosts>>,
          TError,
          Awaited<ReturnType<typeof searchPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchPosts<
  TData = Awaited<ReturnType<typeof searchPosts>>,
  TError = ErrorType<unknown>,
>(
  params: SearchPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Posts
 */

export function useSearchPosts<
  TData = Awaited<ReturnType<typeof searchPosts>>,
  TError = ErrorType<unknown>,
>(
  params: SearchPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get Posts
 * @summary Get Posts
 */
export type getUserPostsResponse200 = {
  data: GetPostsResponse;
  status: 200;
};

export type getUserPostsResponseSuccess = getUserPostsResponse200 & {
  headers: Headers;
};
export type getUserPostsResponse = getUserPostsResponseSuccess;

export const getGetUserPostsUrl = (
  userId: string,
  params?: GetUserPostsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/users/${userId}/posts?${stringifiedParams}`
    : `/users/${userId}/posts`;
};

export const getUserPosts = async (
  userId: string,
  params?: GetUserPostsParams,
  options?: RequestInit,
): Promise<getUserPostsResponse> => {
  return api<getUserPostsResponse>(getGetUserPostsUrl(userId, params), {
    ...options,
    method: 'GET',
  });
};

export const getGetUserPostsInfiniteQueryKey = (
  userId: string,
  params?: GetUserPostsParams,
) => {
  return [
    'infinite',
    `/users/${userId}/posts`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetUserPostsQueryKey = (
  userId: string,
  params?: GetUserPostsParams,
) => {
  return [`/users/${userId}/posts`, ...(params ? [params] : [])] as const;
};

export const getGetUserPostsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserPosts>>,
    GetUserPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData,
        QueryKey,
        GetUserPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserPostsInfiniteQueryKey(userId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserPosts>>,
    QueryKey,
    GetUserPostsParams['after']
  > = ({ signal, pageParam }) =>
    getUserPosts(
      userId,
      { ...params, after: pageParam || params?.['after'] },
      { signal, ...requestOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getUserPosts>>,
    TError,
    TData,
    QueryKey,
    GetUserPostsParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserPostsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserPosts>>
>;
export type GetUserPostsInfiniteQueryError = ErrorType<unknown>;

export function useGetUserPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserPosts>>,
    GetUserPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | GetUserPostsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData,
        QueryKey,
        GetUserPostsParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPosts>>,
          TError,
          Awaited<ReturnType<typeof getUserPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserPosts>>,
    GetUserPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData,
        QueryKey,
        GetUserPostsParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPosts>>,
          TError,
          Awaited<ReturnType<typeof getUserPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserPosts>>,
    GetUserPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData,
        QueryKey,
        GetUserPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Posts
 */

export function useGetUserPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getUserPosts>>,
    GetUserPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getUserPosts>>,
        TError,
        TData,
        QueryKey,
        GetUserPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserPostsInfiniteQueryOptions(
    userId,
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetUserPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserPostsQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserPosts>>> = ({
    signal,
  }) => getUserPosts(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserPosts>>
>;
export type GetUserPostsQueryError = ErrorType<unknown>;

export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | GetUserPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPosts>>,
          TError,
          Awaited<ReturnType<typeof getUserPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPosts>>,
          TError,
          Awaited<ReturnType<typeof getUserPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Posts
 */

export function useGetUserPosts<
  TData = Awaited<ReturnType<typeof getUserPosts>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserPostsQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
