/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  GetNotificationsParams,
  GetNotificationsResponse,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get Notifications
 * @summary Get Notifications
 */
export type getNotificationsResponse200 = {
  data: GetNotificationsResponse;
  status: 200;
};

export type getNotificationsResponseSuccess = getNotificationsResponse200 & {
  headers: Headers;
};
export type getNotificationsResponse = getNotificationsResponseSuccess;

export const getGetNotificationsUrl = (params?: GetNotificationsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/notifications?${stringifiedParams}`
    : `/notifications`;
};

export const getNotifications = async (
  params?: GetNotificationsParams,
  options?: RequestInit,
): Promise<getNotificationsResponse> => {
  return api<getNotificationsResponse>(getGetNotificationsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetNotificationsQueryKey = (
  params?: GetNotificationsParams,
) => {
  return [`/notifications`, ...(params ? [params] : [])] as const;
};

export const getGetNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetNotificationsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getNotifications>>
  > = ({ signal }) => getNotifications(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotifications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNotifications>>
>;
export type GetNotificationsQueryError = ErrorType<unknown>;

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetNotificationsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Notifications
 */

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = ErrorType<unknown>,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetNotificationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Mark All Notifications As Read
 * @summary Mark All Notifications As Read
 */
export type markAllNotificationsAsReadResponse204 = {
  data: void;
  status: 204;
};

export type markAllNotificationsAsReadResponseSuccess =
  markAllNotificationsAsReadResponse204 & {
    headers: Headers;
  };
export type markAllNotificationsAsReadResponse =
  markAllNotificationsAsReadResponseSuccess;

export const getMarkAllNotificationsAsReadUrl = () => {
  return `/notifications/read-all`;
};

export const markAllNotificationsAsRead = async (
  options?: RequestInit,
): Promise<markAllNotificationsAsReadResponse> => {
  return api<markAllNotificationsAsReadResponse>(
    getMarkAllNotificationsAsReadUrl(),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export const getMarkAllNotificationsAsReadMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markAllNotificationsAsRead>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markAllNotificationsAsRead>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['markAllNotificationsAsRead'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markAllNotificationsAsRead>>,
    void
  > = () => {
    return markAllNotificationsAsRead(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MarkAllNotificationsAsReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof markAllNotificationsAsRead>>
>;

export type MarkAllNotificationsAsReadMutationError = ErrorType<unknown>;

/**
 * @summary Mark All Notifications As Read
 */
export const useMarkAllNotificationsAsRead = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markAllNotificationsAsRead>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof markAllNotificationsAsRead>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getMarkAllNotificationsAsReadMutationOptions(options),
    queryClient,
  );
};
/**
 * Mark Notification As Read
 * @summary Mark Notification As Read
 */
export type markNotificationAsReadResponse204 = {
  data: void;
  status: 204;
};

export type markNotificationAsReadResponseSuccess =
  markNotificationAsReadResponse204 & {
    headers: Headers;
  };
export type markNotificationAsReadResponse =
  markNotificationAsReadResponseSuccess;

export const getMarkNotificationAsReadUrl = (notificationId: string) => {
  return `/notifications/${notificationId}/read`;
};

export const markNotificationAsRead = async (
  notificationId: string,
  options?: RequestInit,
): Promise<markNotificationAsReadResponse> => {
  return api<markNotificationAsReadResponse>(
    getMarkNotificationAsReadUrl(notificationId),
    {
      ...options,
      method: 'PATCH',
    },
  );
};

export const getMarkNotificationAsReadMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof markNotificationAsRead>>,
    TError,
    { notificationId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof markNotificationAsRead>>,
  TError,
  { notificationId: string },
  TContext
> => {
  const mutationKey = ['markNotificationAsRead'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof markNotificationAsRead>>,
    { notificationId: string }
  > = (props) => {
    const { notificationId } = props ?? {};

    return markNotificationAsRead(notificationId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MarkNotificationAsReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof markNotificationAsRead>>
>;

export type MarkNotificationAsReadMutationError = ErrorType<unknown>;

/**
 * @summary Mark Notification As Read
 */
export const useMarkNotificationAsRead = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof markNotificationAsRead>>,
      TError,
      { notificationId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof markNotificationAsRead>>,
  TError,
  { notificationId: string },
  TContext
> => {
  return useMutation(
    getMarkNotificationAsReadMutationOptions(options),
    queryClient,
  );
};
