/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  GetConnectionsResponse,
  GetFollowersParams,
  GetFollowingParams,
  GetHandleAvailabilityParams,
  GetHandleAvailabilityResponse,
  GetUserRecommendationsResponse,
  SearchUsersParams,
  SearchUsersResponse,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getHandleAvailabilityResponse200 = {
  data: GetHandleAvailabilityResponse;
  status: 200;
};

export type getHandleAvailabilityResponseSuccess =
  getHandleAvailabilityResponse200 & {
    headers: Headers;
  };
export type getHandleAvailabilityResponse =
  getHandleAvailabilityResponseSuccess;

export const getGetHandleAvailabilityUrl = (
  params: GetHandleAvailabilityParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/handles/availability?${stringifiedParams}`
    : `/handles/availability`;
};

/**
 * 사용자 핸들의 사용 가능 여부를 확인합니다.
 * @summary Get Handle Availability
 */
export const getHandleAvailability = async (
  params: GetHandleAvailabilityParams,
  options?: RequestInit,
): Promise<getHandleAvailabilityResponse> => {
  return api<getHandleAvailabilityResponse>(
    getGetHandleAvailabilityUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetHandleAvailabilityQueryKey = (
  params?: GetHandleAvailabilityParams,
) => {
  return [`/handles/availability`, ...(params ? [params] : [])] as const;
};

export const getGetHandleAvailabilityQueryOptions = <
  TData = Awaited<ReturnType<typeof getHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHandleAvailability>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHandleAvailabilityQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHandleAvailability>>
  > = ({ signal }) =>
    getHandleAvailability(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHandleAvailability>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetHandleAvailabilityQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHandleAvailability>>
>;
export type GetHandleAvailabilityQueryError = ErrorType<unknown>;

export function useGetHandleAvailability<
  TData = Awaited<ReturnType<typeof getHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetHandleAvailabilityParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHandleAvailability>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHandleAvailability>>,
          TError,
          Awaited<ReturnType<typeof getHandleAvailability>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHandleAvailability<
  TData = Awaited<ReturnType<typeof getHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHandleAvailability>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHandleAvailability>>,
          TError,
          Awaited<ReturnType<typeof getHandleAvailability>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetHandleAvailability<
  TData = Awaited<ReturnType<typeof getHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHandleAvailability>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Handle Availability
 */

export function useGetHandleAvailability<
  TData = Awaited<ReturnType<typeof getHandleAvailability>>,
  TError = ErrorType<unknown>,
>(
  params: GetHandleAvailabilityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getHandleAvailability>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetHandleAvailabilityQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type searchUsersResponse200 = {
  data: SearchUsersResponse;
  status: 200;
};

export type searchUsersResponseSuccess = searchUsersResponse200 & {
  headers: Headers;
};
export type searchUsersResponse = searchUsersResponseSuccess;

export const getSearchUsersUrl = (params: SearchUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/search/users?${stringifiedParams}`
    : `/search/users`;
};

/**
 * 검색어로 사용자를 검색합니다.
 * @summary Search Users
 */
export const searchUsers = async (
  params: SearchUsersParams,
  options?: RequestInit,
): Promise<searchUsersResponse> => {
  return api<searchUsersResponse>(getSearchUsersUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getSearchUsersQueryKey = (params?: SearchUsersParams) => {
  return [`/search/users`, ...(params ? [params] : [])] as const;
};

export const getSearchUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof searchUsers>>,
  TError = ErrorType<unknown>,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSearchUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof searchUsers>>> = ({
    signal,
  }) => searchUsers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof searchUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof searchUsers>>
>;
export type SearchUsersQueryError = ErrorType<unknown>;

export function useSearchUsers<
  TData = Awaited<ReturnType<typeof searchUsers>>,
  TError = ErrorType<unknown>,
>(
  params: SearchUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchUsers>>,
          TError,
          Awaited<ReturnType<typeof searchUsers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchUsers<
  TData = Awaited<ReturnType<typeof searchUsers>>,
  TError = ErrorType<unknown>,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchUsers>>,
          TError,
          Awaited<ReturnType<typeof searchUsers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchUsers<
  TData = Awaited<ReturnType<typeof searchUsers>>,
  TError = ErrorType<unknown>,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search Users
 */

export function useSearchUsers<
  TData = Awaited<ReturnType<typeof searchUsers>>,
  TError = ErrorType<unknown>,
>(
  params: SearchUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof searchUsers>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSearchUsersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getRecommendationsResponse200 = {
  data: GetUserRecommendationsResponse;
  status: 200;
};

export type getRecommendationsResponseSuccess =
  getRecommendationsResponse200 & {
    headers: Headers;
  };
export type getRecommendationsResponse = getRecommendationsResponseSuccess;

export const getGetRecommendationsUrl = () => {
  return `/users/recommendations`;
};

/**
 * 팔로우할 만한 사용자 목록을 추천합니다.
 * @summary Get Recommendations
 */
export const getRecommendations = async (
  options?: RequestInit,
): Promise<getRecommendationsResponse> => {
  return api<getRecommendationsResponse>(getGetRecommendationsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetRecommendationsQueryKey = () => {
  return [`/users/recommendations`] as const;
};

export const getGetRecommendationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getRecommendations>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRecommendationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecommendations>>
  > = ({ signal }) => getRecommendations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecommendations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecommendationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecommendations>>
>;
export type GetRecommendationsQueryError = ErrorType<unknown>;

export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecommendations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecommendations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecommendations>>,
          TError,
          Awaited<ReturnType<typeof getRecommendations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecommendations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Recommendations
 */

export function useGetRecommendations<
  TData = Awaited<ReturnType<typeof getRecommendations>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecommendations>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecommendationsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type followUserResponse200 = {
  data: void;
  status: 200;
};

export type followUserResponseSuccess = followUserResponse200 & {
  headers: Headers;
};
export type followUserResponse = followUserResponseSuccess;

export const getFollowUserUrl = (followeeId: string) => {
  return `/users/follow/${followeeId}`;
};

/**
 * 사용자를 팔로우합니다.
 * @summary Follow User
 */
export const followUser = async (
  followeeId: string,
  options?: RequestInit,
): Promise<followUserResponse> => {
  return api<followUserResponse>(getFollowUserUrl(followeeId), {
    ...options,
    method: 'POST',
  });
};

export const getFollowUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof followUser>>,
    TError,
    { followeeId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof followUser>>,
  TError,
  { followeeId: string },
  TContext
> => {
  const mutationKey = ['followUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof followUser>>,
    { followeeId: string }
  > = (props) => {
    const { followeeId } = props ?? {};

    return followUser(followeeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FollowUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof followUser>>
>;

export type FollowUserMutationError = ErrorType<unknown>;

/**
 * @summary Follow User
 */
export const useFollowUser = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof followUser>>,
      TError,
      { followeeId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof followUser>>,
  TError,
  { followeeId: string },
  TContext
> => {
  return useMutation(getFollowUserMutationOptions(options), queryClient);
};
export type unfollowUserResponse204 = {
  data: void;
  status: 204;
};

export type unfollowUserResponseSuccess = unfollowUserResponse204 & {
  headers: Headers;
};
export type unfollowUserResponse = unfollowUserResponseSuccess;

export const getUnfollowUserUrl = (followeeId: string) => {
  return `/users/unfollow/${followeeId}`;
};

/**
 * 사용자 팔로우를 취소합니다.
 * @summary Unfollow User
 */
export const unfollowUser = async (
  followeeId: string,
  options?: RequestInit,
): Promise<unfollowUserResponse> => {
  return api<unfollowUserResponse>(getUnfollowUserUrl(followeeId), {
    ...options,
    method: 'DELETE',
  });
};

export const getUnfollowUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unfollowUser>>,
    TError,
    { followeeId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unfollowUser>>,
  TError,
  { followeeId: string },
  TContext
> => {
  const mutationKey = ['unfollowUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unfollowUser>>,
    { followeeId: string }
  > = (props) => {
    const { followeeId } = props ?? {};

    return unfollowUser(followeeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnfollowUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof unfollowUser>>
>;

export type UnfollowUserMutationError = ErrorType<unknown>;

/**
 * @summary Unfollow User
 */
export const useUnfollowUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unfollowUser>>,
      TError,
      { followeeId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof unfollowUser>>,
  TError,
  { followeeId: string },
  TContext
> => {
  return useMutation(getUnfollowUserMutationOptions(options), queryClient);
};
export type getFollowersResponse200 = {
  data: GetConnectionsResponse;
  status: 200;
};

export type getFollowersResponseSuccess = getFollowersResponse200 & {
  headers: Headers;
};
export type getFollowersResponse = getFollowersResponseSuccess;

export const getGetFollowersUrl = (
  userId: string,
  params?: GetFollowersParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/users/${userId}/followers?${stringifiedParams}`
    : `/users/${userId}/followers`;
};

/**
 * 사용자를 팔로우하는 사용자 목록을 조회합니다.
 * @summary Get Followers
 */
export const getFollowers = async (
  userId: string,
  params?: GetFollowersParams,
  options?: RequestInit,
): Promise<getFollowersResponse> => {
  return api<getFollowersResponse>(getGetFollowersUrl(userId, params), {
    ...options,
    method: 'GET',
  });
};

export const getGetFollowersInfiniteQueryKey = (
  userId: string,
  params?: GetFollowersParams,
) => {
  return [
    'infinite',
    `/users/${userId}/followers`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetFollowersQueryKey = (
  userId: string,
  params?: GetFollowersParams,
) => {
  return [`/users/${userId}/followers`, ...(params ? [params] : [])] as const;
};

export const getGetFollowersInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowers>>,
    GetFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowers>>,
        TError,
        TData,
        QueryKey,
        GetFollowersParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFollowersInfiniteQueryKey(userId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFollowers>>,
    QueryKey,
    GetFollowersParams['after']
  > = ({ signal, pageParam }) =>
    getFollowers(
      userId,
      { ...params, after: pageParam ?? params?.['after'] },
      { signal, ...requestOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getFollowers>>,
    TError,
    TData,
    QueryKey,
    GetFollowersParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFollowersInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFollowers>>
>;
export type GetFollowersInfiniteQueryError = ErrorType<unknown>;

export function useGetFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowers>>,
    GetFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | GetFollowersParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowers>>,
        TError,
        TData,
        QueryKey,
        GetFollowersParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowers>>,
          TError,
          Awaited<ReturnType<typeof getFollowers>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowers>>,
    GetFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowers>>,
        TError,
        TData,
        QueryKey,
        GetFollowersParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowers>>,
          TError,
          Awaited<ReturnType<typeof getFollowers>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowers>>,
    GetFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowers>>,
        TError,
        TData,
        QueryKey,
        GetFollowersParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Followers
 */

export function useGetFollowersInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowers>>,
    GetFollowersParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowers>>,
        TError,
        TData,
        QueryKey,
        GetFollowersParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFollowersInfiniteQueryOptions(
    userId,
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetFollowersQueryOptions = <
  TData = Awaited<ReturnType<typeof getFollowers>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFollowersQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFollowers>>> = ({
    signal,
  }) => getFollowers(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFollowers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFollowersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFollowers>>
>;
export type GetFollowersQueryError = ErrorType<unknown>;

export function useGetFollowers<
  TData = Awaited<ReturnType<typeof getFollowers>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | GetFollowersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowers>>,
          TError,
          Awaited<ReturnType<typeof getFollowers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowers<
  TData = Awaited<ReturnType<typeof getFollowers>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowers>>,
          TError,
          Awaited<ReturnType<typeof getFollowers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowers<
  TData = Awaited<ReturnType<typeof getFollowers>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Followers
 */

export function useGetFollowers<
  TData = Awaited<ReturnType<typeof getFollowers>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowers>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFollowersQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getFollowingResponse200 = {
  data: GetConnectionsResponse;
  status: 200;
};

export type getFollowingResponseSuccess = getFollowingResponse200 & {
  headers: Headers;
};
export type getFollowingResponse = getFollowingResponseSuccess;

export const getGetFollowingUrl = (
  userId: string,
  params?: GetFollowingParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/users/${userId}/following?${stringifiedParams}`
    : `/users/${userId}/following`;
};

/**
 * 사용자가 팔로우하는 사용자 목록을 조회합니다.
 * @summary Get Following
 */
export const getFollowing = async (
  userId: string,
  params?: GetFollowingParams,
  options?: RequestInit,
): Promise<getFollowingResponse> => {
  return api<getFollowingResponse>(getGetFollowingUrl(userId, params), {
    ...options,
    method: 'GET',
  });
};

export const getGetFollowingInfiniteQueryKey = (
  userId: string,
  params?: GetFollowingParams,
) => {
  return [
    'infinite',
    `/users/${userId}/following`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetFollowingQueryKey = (
  userId: string,
  params?: GetFollowingParams,
) => {
  return [`/users/${userId}/following`, ...(params ? [params] : [])] as const;
};

export const getGetFollowingInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowing>>,
    GetFollowingParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowing>>,
        TError,
        TData,
        QueryKey,
        GetFollowingParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFollowingInfiniteQueryKey(userId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFollowing>>,
    QueryKey,
    GetFollowingParams['after']
  > = ({ signal, pageParam }) =>
    getFollowing(
      userId,
      { ...params, after: pageParam ?? params?.['after'] },
      { signal, ...requestOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getFollowing>>,
    TError,
    TData,
    QueryKey,
    GetFollowingParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFollowingInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFollowing>>
>;
export type GetFollowingInfiniteQueryError = ErrorType<unknown>;

export function useGetFollowingInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowing>>,
    GetFollowingParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | GetFollowingParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowing>>,
        TError,
        TData,
        QueryKey,
        GetFollowingParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowing>>,
          TError,
          Awaited<ReturnType<typeof getFollowing>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowingInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowing>>,
    GetFollowingParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowing>>,
        TError,
        TData,
        QueryKey,
        GetFollowingParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowing>>,
          TError,
          Awaited<ReturnType<typeof getFollowing>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowingInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowing>>,
    GetFollowingParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowing>>,
        TError,
        TData,
        QueryKey,
        GetFollowingParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Following
 */

export function useGetFollowingInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getFollowing>>,
    GetFollowingParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getFollowing>>,
        TError,
        TData,
        QueryKey,
        GetFollowingParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFollowingInfiniteQueryOptions(
    userId,
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetFollowingQueryOptions = <
  TData = Awaited<ReturnType<typeof getFollowing>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFollowingQueryKey(userId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFollowing>>> = ({
    signal,
  }) => getFollowing(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFollowing>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFollowingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFollowing>>
>;
export type GetFollowingQueryError = ErrorType<unknown>;

export function useGetFollowing<
  TData = Awaited<ReturnType<typeof getFollowing>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | GetFollowingParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowing>>,
          TError,
          Awaited<ReturnType<typeof getFollowing>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowing<
  TData = Awaited<ReturnType<typeof getFollowing>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFollowing>>,
          TError,
          Awaited<ReturnType<typeof getFollowing>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFollowing<
  TData = Awaited<ReturnType<typeof getFollowing>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Following
 */

export function useGetFollowing<
  TData = Awaited<ReturnType<typeof getFollowing>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetFollowingParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFollowing>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFollowingQueryOptions(userId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
