export enum ErrorCode {
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',

  BAD_REQUEST = 'BAD_REQUEST',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  OAUTH2_ACCOUNT_CANNOT_BE_DELETED = 'OAUTH2_ACCOUNT_CANNOT_BE_DELETED',
  OAUTH2_ACCOUNT_CANNOT_BE_LINKED = 'OAUTH2_ACCOUNT_CANNOT_BE_LINKED',
  INVALID_EMAIL_VERIFICATION_TOKEN = 'INVALID_EMAIL_VERIFICATION_TOKEN',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  EMAIL_SENDING_FAILED = 'EMAIL_SENDING_FAILED',
  INVALID_PASSWORD_RESET_TOKEN = 'INVALID_PASSWORD_RESET_TOKEN',
  EXPIRED_PASSWORD_RESET_TOKEN = 'EXPIRED_PASSWORD_RESET_TOKEN',
  INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD',
  CAPTCHA_VERIFICATION_FAILED = 'CAPTCHA_VERIFICATION_FAILED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_CANNOT_FOLLOW_SELF = 'USER_CANNOT_FOLLOW_SELF',
  USER_CANNOT_BE_DELETED = 'USER_CANNOT_BE_DELETED',
  HANDLE_NOT_SET = 'HANDLE_NOT_SET',

  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_HANDLE_ALREADY_EXISTS = 'PROJECT_HANDLE_ALREADY_EXISTS',
  PROJECT_OWNER_CANNOT_BE_MODIFIED = 'PROJECT_OWNER_CANNOT_BE_MODIFIED',
  PROJECT_OWNER_CANNOT_LEAVE = 'PROJECT_OWNER_CANNOT_LEAVE',
  TEAMMATE_NOT_FOUND = 'TEAMMATE_NOT_FOUND',
  PROJECT_INVITATION_NOT_FOUND = 'PROJECT_INVITATION_NOT_FOUND',
  PROJECT_INVITATION_EXPIRED = 'PROJECT_INVITATION_EXPIRED',
  PROJECT_INVITATION_ALREADY_EXISTS = 'PROJECT_INVITATION_ALREADY_EXISTS',
  PROJECT_JOIN_NOT_ALLOWED = 'PROJECT_JOIN_NOT_ALLOWED',
  PROJECT_JOIN_POLICY_NOT_ALLOWED = 'PROJECT_JOIN_POLICY_NOT_ALLOWED',
  PROJECT_ALREADY_TEAMMATE = 'PROJECT_ALREADY_TEAMMATE',
  PROJECT_JOIN_REQUEST_ALREADY_EXISTS = 'PROJECT_JOIN_REQUEST_ALREADY_EXISTS',
  PROJECT_JOIN_REQUEST_NOT_FOUND = 'PROJECT_JOIN_REQUEST_NOT_FOUND',

  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  POST_NOT_FOUND = 'POST_NOT_FOUND',
  POST_REFERENCE_SELF = 'POST_REFERENCE_SELF',
  POST_REFERENCE_LIMIT_EXCEEDED = 'POST_REFERENCE_LIMIT_EXCEEDED',
  POST_REPORT_ALREADY_EXISTS = 'POST_REPORT_ALREADY_EXISTS',
  POST_REPORT_ALREADY_REVIEWED = 'POST_REPORT_ALREADY_REVIEWED',
  POST_REPORT_NOT_FOUND = 'POST_REPORT_NOT_FOUND',
  POST_PIN_LIMIT_EXCEEDED = 'POST_PIN_LIMIT_EXCEEDED',

  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_NOT_ALLOWED = 'COMMENT_NOT_ALLOWED',

  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_NOT_UPLOADED = 'MEDIA_NOT_UPLOADED',
  MEDIA_TOO_LARGE = 'MEDIA_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',

  TAG_LIMIT_EXCEEDED = 'TAG_LIMIT_EXCEEDED',
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',
  TAG_ALREADY_EXISTS = 'TAG_ALREADY_EXISTS',
  TAG_POOL_MISMATCH = 'TAG_POOL_MISMATCH',

  COLLECTION_NOT_FOUND = 'COLLECTION_NOT_FOUND',
  COLLECTION_POST_ALREADY_EXISTS = 'COLLECTION_POST_ALREADY_EXISTS',
  COLLECTION_POST_NOT_FOUND = 'COLLECTION_POST_NOT_FOUND',

  POST_SERIES_NOT_FOUND = 'POST_SERIES_NOT_FOUND',
  POST_SERIES_POST_ALREADY_EXISTS = 'POST_SERIES_POST_ALREADY_EXISTS',
  POST_SERIES_POST_NOT_FOUND = 'POST_SERIES_POST_NOT_FOUND',
  POST_SERIES_POST_OWNERSHIP_MISMATCH = 'POST_SERIES_POST_OWNERSHIP_MISMATCH',
  POST_SERIES_POST_LIMIT_EXCEEDED = 'POST_SERIES_POST_LIMIT_EXCEEDED',

  PROMOTION_NOT_FOUND = 'PROMOTION_NOT_FOUND',
  PROMOTION_SIGNUP_ATTACHMENT_INVALID = 'PROMOTION_SIGNUP_ATTACHMENT_INVALID',

  CHANNEL_TALK_MEMBER_HASH_FAILED = 'CHANNEL_TALK_MEMBER_HASH_FAILED',

  // 아래 두 코드는 dead code로 표시된 provider/message 도메인 소속이며 라이브
  // 컨트롤러에서 절대 던져지지 않는다. apps/web/src/app/_legacy만 참조한다.
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  MESSAGE_TO_SELF = 'MESSAGE_TO_SELF',
}

const DIGEST_PREFIX = 'SYNC_';

export default class SyncError extends Error {
  public readonly code: ErrorCode;

  /**
   * 서버 컴포넌트에서 던진 에러는 프로덕션에서 message가 지워진 채
   * digest만 error.tsx로 전달된다. Next.js는 이미 digest가 있으면 그 값을
   * 그대로 보존하므로(create-error-handler), 에러 화면이 원인을 구분할 수
   * 있도록 코드를 digest에 실어 보낸다.
   */
  public readonly digest: string;

  constructor(message: string, code: ErrorCode) {
    super(message);

    Object.setPrototypeOf(this, SyncError.prototype);
    Error.captureStackTrace(this, SyncError);

    this.code = code;
    this.digest = `${DIGEST_PREFIX}${code}`;
  }
}

export function getErrorCodeFromDigest(digest?: string): ErrorCode | null {
  if (digest === undefined || !digest.startsWith(DIGEST_PREFIX)) {
    return null;
  }

  const code = digest.slice(DIGEST_PREFIX.length);

  return (
    Object.values(ErrorCode).find((errorCode) => errorCode === code) ?? null
  );
}
