/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  GetBookmarkedPostsParams,
  GetBookmarkedPostsResponse,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get Bookmarked Posts
 * @summary Get Bookmarked Posts
 */
export type getBookmarkedPostsResponse200 = {
  data: GetBookmarkedPostsResponse;
  status: 200;
};

export type getBookmarkedPostsResponseSuccess =
  getBookmarkedPostsResponse200 & {
    headers: Headers;
  };
export type getBookmarkedPostsResponse = getBookmarkedPostsResponseSuccess;

export const getGetBookmarkedPostsUrl = (params?: GetBookmarkedPostsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/bookmarks/posts?${stringifiedParams}`
    : `/bookmarks/posts`;
};

export const getBookmarkedPosts = async (
  params?: GetBookmarkedPostsParams,
  options?: RequestInit,
): Promise<getBookmarkedPostsResponse> => {
  return api<getBookmarkedPostsResponse>(getGetBookmarkedPostsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetBookmarkedPostsInfiniteQueryKey = (
  params?: GetBookmarkedPostsParams,
) => {
  return ['infinite', `/bookmarks/posts`, ...(params ? [params] : [])] as const;
};

export const getGetBookmarkedPostsQueryKey = (
  params?: GetBookmarkedPostsParams,
) => {
  return [`/bookmarks/posts`, ...(params ? [params] : [])] as const;
};

export const getGetBookmarkedPostsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    GetBookmarkedPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData,
        QueryKey,
        GetBookmarkedPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBookmarkedPostsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    QueryKey,
    GetBookmarkedPostsParams['after']
  > = ({ signal, pageParam }) =>
    getBookmarkedPosts(
      { ...params, after: pageParam || params?.['after'] },
      { signal, ...requestOptions },
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    TError,
    TData,
    QueryKey,
    GetBookmarkedPostsParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookmarkedPostsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBookmarkedPosts>>
>;
export type GetBookmarkedPostsInfiniteQueryError = ErrorType<unknown>;

export function useGetBookmarkedPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    GetBookmarkedPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetBookmarkedPostsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData,
        QueryKey,
        GetBookmarkedPostsParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkedPosts>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkedPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookmarkedPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    GetBookmarkedPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData,
        QueryKey,
        GetBookmarkedPostsParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkedPosts>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkedPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookmarkedPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    GetBookmarkedPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData,
        QueryKey,
        GetBookmarkedPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Bookmarked Posts
 */

export function useGetBookmarkedPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    GetBookmarkedPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData,
        QueryKey,
        GetBookmarkedPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBookmarkedPostsInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetBookmarkedPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBookmarkedPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBookmarkedPostsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBookmarkedPosts>>
  > = ({ signal }) => getBookmarkedPosts(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBookmarkedPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookmarkedPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBookmarkedPosts>>
>;
export type GetBookmarkedPostsQueryError = ErrorType<unknown>;

export function useGetBookmarkedPosts<
  TData = Awaited<ReturnType<typeof getBookmarkedPosts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetBookmarkedPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkedPosts>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkedPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookmarkedPosts<
  TData = Awaited<ReturnType<typeof getBookmarkedPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBookmarkedPosts>>,
          TError,
          Awaited<ReturnType<typeof getBookmarkedPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBookmarkedPosts<
  TData = Awaited<ReturnType<typeof getBookmarkedPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Bookmarked Posts
 */

export function useGetBookmarkedPosts<
  TData = Awaited<ReturnType<typeof getBookmarkedPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetBookmarkedPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBookmarkedPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBookmarkedPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Bookmark Post
 * @summary Bookmark Post
 */
export type bookmarkPostResponse200 = {
  data: void;
  status: 200;
};

export type bookmarkPostResponseSuccess = bookmarkPostResponse200 & {
  headers: Headers;
};
export type bookmarkPostResponse = bookmarkPostResponseSuccess;

export const getBookmarkPostUrl = (postId: string) => {
  return `/posts/${postId}/bookmarks`;
};

export const bookmarkPost = async (
  postId: string,
  options?: RequestInit,
): Promise<bookmarkPostResponse> => {
  return api<bookmarkPostResponse>(getBookmarkPostUrl(postId), {
    ...options,
    method: 'POST',
  });
};

export const getBookmarkPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bookmarkPost>>,
    TError,
    { postId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bookmarkPost>>,
  TError,
  { postId: string },
  TContext
> => {
  const mutationKey = ['bookmarkPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bookmarkPost>>,
    { postId: string }
  > = (props) => {
    const { postId } = props ?? {};

    return bookmarkPost(postId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BookmarkPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof bookmarkPost>>
>;

export type BookmarkPostMutationError = ErrorType<unknown>;

/**
 * @summary Bookmark Post
 */
export const useBookmarkPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof bookmarkPost>>,
      TError,
      { postId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof bookmarkPost>>,
  TError,
  { postId: string },
  TContext
> => {
  return useMutation(getBookmarkPostMutationOptions(options), queryClient);
};
/**
 * Unbookmark Post
 * @summary Unbookmark Post
 */
export type unbookmarkPostResponse204 = {
  data: void;
  status: 204;
};

export type unbookmarkPostResponseSuccess = unbookmarkPostResponse204 & {
  headers: Headers;
};
export type unbookmarkPostResponse = unbookmarkPostResponseSuccess;

export const getUnbookmarkPostUrl = (postId: string) => {
  return `/posts/${postId}/bookmarks`;
};

export const unbookmarkPost = async (
  postId: string,
  options?: RequestInit,
): Promise<unbookmarkPostResponse> => {
  return api<unbookmarkPostResponse>(getUnbookmarkPostUrl(postId), {
    ...options,
    method: 'DELETE',
  });
};

export const getUnbookmarkPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unbookmarkPost>>,
    TError,
    { postId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unbookmarkPost>>,
  TError,
  { postId: string },
  TContext
> => {
  const mutationKey = ['unbookmarkPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unbookmarkPost>>,
    { postId: string }
  > = (props) => {
    const { postId } = props ?? {};

    return unbookmarkPost(postId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnbookmarkPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof unbookmarkPost>>
>;

export type UnbookmarkPostMutationError = ErrorType<unknown>;

/**
 * @summary Unbookmark Post
 */
export const useUnbookmarkPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unbookmarkPost>>,
      TError,
      { postId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof unbookmarkPost>>,
  TError,
  { postId: string },
  TContext
> => {
  return useMutation(getUnbookmarkPostMutationOptions(options), queryClient);
};
